//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplications.Utilities.Scheduling {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplications.Utilities.Scheduling.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an aggregate schedule out of schedules which have different options..
        /// </summary>
        internal static string AggregateSchedule_Different_Options {
            get {
                return ResourceManager.GetString("AggregateSchedule_Different_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule &apos;{0}&apos; returned a DateTime in the past..
        /// </summary>
        internal static string AggregateSchedule_Next_Schedule_DateTime_Past {
            get {
                return ResourceManager.GetString("AggregateSchedule_Next_Schedule_DateTime_Past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid task status &apos;{0}&apos; in scheduled action continuation..
        /// </summary>
        internal static string ScheduledAction_ExecuteAsync_Invalid_Task_Status {
            get {
                return ResourceManager.GetString("ScheduledAction_ExecuteAsync_Invalid_Task_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to recalculate next due date for schedule..
        /// </summary>
        internal static string ScheduledAction_RecalculateNextDue_Failed {
            get {
                return ResourceManager.GetString("ScheduledAction_RecalculateNextDue_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scheduled function returned a null task..
        /// </summary>
        internal static string ScheduledFunction_DoExecuteAsync_Null_Task {
            get {
                return ResourceManager.GetString("ScheduledFunction_DoExecuteAsync_Null_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default maximum history for a scheduler cannot be negative..
        /// </summary>
        internal static string Scheduler_DefaultMaximumHistory_Negative {
            get {
                return ResourceManager.GetString("Scheduler_DefaultMaximumHistory_Negative", resourceCulture);
            }
        }
    }
}
