//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplications.Utilities.Service.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplications.Utilities.Service.Client.ClientResources", typeof(ClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling command....
        /// </summary>
        public static string ConsoleClient_RunAsync_Cancelling {
            get {
                return ResourceManager.GetString("ConsoleClient_RunAsync_Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connected to {1}.
        /// </summary>
        public static string ConsoleClient_RunAsync_ConnectedTitle {
            get {
                return ResourceManager.GetString("ConsoleClient_RunAsync_ConnectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}....
        /// </summary>
        public static string ConsoleClient_RunAsync_ConnectingToService {
            get {
                return ResourceManager.GetString("ConsoleClient_RunAsync_ConnectingToService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid service name or pipe to connect to; or press enter to use the first service found....
        /// </summary>
        public static string ConsoleClient_RunAsync_EnterServiceName {
            get {
                return ResourceManager.GetString("ConsoleClient_RunAsync_EnterServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        public static string ConsoleClient_RunAsync_PressAnyKeyContinue {
            get {
                return ResourceManager.GetString("ConsoleClient_RunAsync_PressAnyKeyContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to finish..
        /// </summary>
        public static string ConsoleClient_RunAsync_PressAnyKeyExit {
            get {
                return ResourceManager.GetString("ConsoleClient_RunAsync_PressAnyKeyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for service... press any key to stop.
        /// </summary>
        public static string ConsoleClient_RunAsync_ScanningForService {
            get {
                return ResourceManager.GetString("ConsoleClient_RunAsync_ScanningForService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out connecting to {0}..
        /// </summary>
        public static string ConsoleClient_RunAsync_TimedOut {
            get {
                return ResourceManager.GetString("ConsoleClient_RunAsync_TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command response was missing sequence elements..
        /// </summary>
        public static string Err_ConnectedCommand_Received_MissingSequenceElements {
            get {
                return ResourceManager.GetString("Err_ConnectedCommand_Received_MissingSequenceElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occurred on the current named pipe client, closing..
        /// </summary>
        public static string Err_NamedPipeClient_Failed {
            get {
                return ResourceManager.GetString("Err_NamedPipeClient_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client has connected to the service &apos;{0}&apos;..
        /// </summary>
        public static string Not_NamedPipeClient_Connection {
            get {
                return ResourceManager.GetString("Not_NamedPipeClient_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate sequence element recieved. Will be ignored..
        /// </summary>
        public static string Wrn_ConnectedCommand_Received_DuplicateSequence {
            get {
                return ResourceManager.GetString("Wrn_ConnectedCommand_Received_DuplicateSequence", resourceCulture);
            }
        }
    }
}
