//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplications.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplications.Utilities.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result is the wrong type.
        /// </summary>
        internal static string ApmWrap_Unwrap_ResultWrongType {
            get {
                return ResourceManager.GetString("ApmWrap_Unwrap_ResultWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration cannot be negative.
        /// </summary>
        internal static string AsyncDebounced_DurationNegative {
            get {
                return ResourceManager.GetString("AsyncDebounced_DurationNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum gap cannot be negative.
        /// </summary>
        internal static string AsyncDebounced_MinimumGapNegative {
            get {
                return ResourceManager.GetString("AsyncDebounced_MinimumGapNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set a result only once.
        /// </summary>
        internal static string AsyncResult_SetAsCompleted_CanOnlySetResultOnce {
            get {
                return ResourceManager.GetString("AsyncResult_SetAsCompleted_CanOnlySetResultOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified duration must be greater than zero..
        /// </summary>
        internal static string BufferedAction_BufferedAction_Invalid_Duration {
            get {
                return ResourceManager.GetString("BufferedAction_BufferedAction_Invalid_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache expiry must be at least 1s..
        /// </summary>
        internal static string CachingQueue_ExpiryTooShort {
            get {
                return ResourceManager.GetString("CachingQueue_ExpiryTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum entries must be at least 1..
        /// </summary>
        internal static string CachingQueue_MaxEntriesLessThanOne {
            get {
                return ResourceManager.GetString("CachingQueue_MaxEntriesLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action returned a null Task.
        /// </summary>
        internal static string CancelableTask_CancelableTask_NullTask {
            get {
                return ResourceManager.GetString("CancelableTask_CancelableTask_NullTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be null or whitespace.
        /// </summary>
        internal static string ColorHelper_SetName_NameNullOrWhitespace {
            get {
                return ResourceManager.GetString("ColorHelper_SetName_NameNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date time supplied to a CombGuid cannot be before &apos;{0}&apos; UTC..
        /// </summary>
        internal static string CombGuid_InvalidDateTime_TooEarly {
            get {
                return ResourceManager.GetString("CombGuid_InvalidDateTime_TooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Utilities configuration system cannot be mixed with non-extended configuration elements.  The &apos;{0}&apos; type does not descend from one of the enhanced configuration element types..
        /// </summary>
        internal static string ConfigurationElement_Init_Invalid_Configuration_Property_Type {
            get {
                return ResourceManager.GetString("ConfigurationElement_Init_Invalid_Configuration_Property_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set a configuration element collection using a key &apos;{0}&apos; that does not match the configuration element&apos;s key &apos;{1}&apos;..
        /// </summary>
        internal static string ConfigurationElementCollection_SetElement_KeyMismatch {
            get {
                return ResourceManager.GetString("ConfigurationElementCollection_SetElement_KeyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current configuration section is not associated with a configuration..
        /// </summary>
        internal static string ConfigurationSection_Save_No_Configuration {
            get {
                return ResourceManager.GetString("ConfigurationSection_Save_No_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration system could not find a constructor with the relevant parameters when trying to create an object of type &apos;{0}&apos;..
        /// </summary>
        internal static string ConstructorConfigurationElement_GetConstructor_CannotFindConstructor {
            get {
                return ResourceManager.GetString("ConstructorConfigurationElement_GetConstructor_CannotFindConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration system found a number of potential constructor matches when trying to create an object of type &apos;{0}&apos;..
        /// </summary>
        internal static string ConstructorConfigurationElement_GetConstructor_ConstructorIsAmbiguous {
            get {
                return ResourceManager.GetString("ConstructorConfigurationElement_GetConstructor_ConstructorIsAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration system cannot assign the created type &apos;{0}&apos; to the required type &apos;{1}&apos;..
        /// </summary>
        internal static string ConstructorConfigurationElement_GetConstructor_CreatedTypeNotAssignable {
            get {
                return ResourceManager.GetString("ConstructorConfigurationElement_GetConstructor_CreatedTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an instance of the object as no type was specified..
        /// </summary>
        internal static string ConstructorConfigurationElement_GetConstructor_Missing_Type {
            get {
                return ResourceManager.GetString("ConstructorConfigurationElement_GetConstructor_Missing_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot close the ContextStack cleaner region on thread &apos;{0}&apos; as it was created on thread &apos;{1}&apos;..
        /// </summary>
        internal static string ContextStack_Dispose_CannotCloseCleanerRegion {
            get {
                return ResourceManager.GetString("ContextStack_Dispose_CannotCloseCleanerRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot close the ContextStack region on thread &apos;{0}&apos; as it was created on thread &apos;{1}&apos;..
        /// </summary>
        internal static string ContextStack_Dispose_CannotCloseRegion {
            get {
                return ResourceManager.GetString("ContextStack_Dispose_CannotCloseRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;cultureInfo&apos; can not be null.
        /// </summary>
        internal static string CultureHelper_CultureInfoCannotBeNull {
            get {
                return ResourceManager.GetString("CultureHelper_CultureInfoCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;currencyISO&apos; can not be null.
        /// </summary>
        internal static string CultureHelper_CurrencyIsoCannotBeNull {
            get {
                return ResourceManager.GetString("CultureHelper_CurrencyIsoCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;isoCode&apos; can not be null.
        /// </summary>
        internal static string CultureHelper_IsoCodeCannotBeNull {
            get {
                return ResourceManager.GetString("CultureHelper_IsoCodeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;name&apos; can not be null.
        /// </summary>
        internal static string CultureHelper_NameCannotBeNull {
            get {
                return ResourceManager.GetString("CultureHelper_NameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;regionInfo&apos; can not be null.
        /// </summary>
        internal static string CultureHelper_RegionInfoCannotBeNull {
            get {
                return ResourceManager.GetString("CultureHelper_RegionInfoCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency: {0}, Code: {1}, ISO: {2}.
        /// </summary>
        internal static string CurrencyInfo_ToString {
            get {
                return ResourceManager.GetString("CurrencyInfo_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the currency information from the ISO 4217 file &apos;{0}&apos;..
        /// </summary>
        internal static string CurrencyInfoProvider_CurrencyInfoProvider_DataInvalid {
            get {
                return ResourceManager.GetString("CurrencyInfoProvider_CurrencyInfoProvider_DataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path to the ISO 4217 file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string CurrencyInfoProvider_CurrencyInfoProvider_FileNotFound {
            get {
                return ResourceManager.GetString("CurrencyInfoProvider_CurrencyInfoProvider_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal exception occurred whilst trying to load the ISO 4217 file &apos;{0}..
        /// </summary>
        internal static string CurrencyInfoProvider_CurrencyInfoProvider_LoadError {
            get {
                return ResourceManager.GetString("CurrencyInfoProvider_CurrencyInfoProvider_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue empty..
        /// </summary>
        internal static string CyclicQueue_QueueEmpty {
            get {
                return ResourceManager.GetString("CyclicQueue_QueueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object cannot have a dependency on itself..
        /// </summary>
        internal static string DependencyGraph_Add_SelfDepends {
            get {
                return ResourceManager.GetString("DependencyGraph_Add_SelfDepends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value given is not in the graph.
        /// </summary>
        internal static string DependencyGraph_ValueNotInGraph {
            get {
                return ResourceManager.GetString("DependencyGraph_ValueNotInGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse the string &apos;{0}&apos; to a Duration..
        /// </summary>
        internal static string DurationConverter_ConvertFrom_CannotParse {
            get {
                return ResourceManager.GetString("DurationConverter_ConvertFrom_CannotParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot safely flush the default enhanced memory cache..
        /// </summary>
        internal static string EnhancedMemoryCache_Clear_CannotSafelyFlush {
            get {
                return ResourceManager.GetString("EnhancedMemoryCache_Clear_CannotSafelyFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot safely dispose the default enhanced memory cache..
        /// </summary>
        internal static string EnhancedMemoryCache_Dispose_CannotSafelyDispose {
            get {
                return ResourceManager.GetString("EnhancedMemoryCache_Dispose_CannotSafelyDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action expression is expected to return void..
        /// </summary>
        internal static string ExpressionExtensions_ActionReturnsNonVoid {
            get {
                return ResourceManager.GetString("ExpressionExtensions_ActionReturnsNonVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source enumerable is not of an enumerable type.
        /// </summary>
        internal static string ExpressionExtensions_ForEach_SourceNotEnumerable {
            get {
                return ResourceManager.GetString("ExpressionExtensions_ForEach_SourceNotEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function expression is expected to not return void..
        /// </summary>
        internal static string ExpressionExtensions_FuncReturnsVoid {
            get {
                return ResourceManager.GetString("ExpressionExtensions_FuncReturnsVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression does not have the same number of parameters as the delegate..
        /// </summary>
        internal static string ExpressionExtensions_GetDelegateExpression_ParameterCountMismatch {
            get {
                return ResourceManager.GetString("ExpressionExtensions_GetDelegateExpression_ParameterCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type parameter must be derived from System.Delegate..
        /// </summary>
        internal static string ExpressionExtensions_GetDelegateExpression_TypeMustBeDelegate {
            get {
                return ResourceManager.GetString("ExpressionExtensions_GetDelegateExpression_TypeMustBeDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression had the wrong number of parameters..
        /// </summary>
        internal static string ExpressionExtensions_ParameterCount {
            get {
                return ResourceManager.GetString("ExpressionExtensions_ParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; value of the {1} enum does could not be cleared with the value &apos;{2}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_Clear_CouldNotClearFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Clear_CouldNotClearFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not combine flags of type &apos;{0}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_Combine_CouldNotCombineFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Combine_CouldNotCombineFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} enum does not contain the name &apos;{1}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_DoesNotContainName {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_DoesNotContainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} enum does not contain the raw value &apos;{1}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_DoesNotContainRawValue {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_DoesNotContainRawValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} enum does not contain the value &apos;{1}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_DoesNotContainValue {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_DoesNotContainValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; value of the {1} enum does could not be intersected with the value &apos;{2}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_Intersect_CouldNotIntersectFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Intersect_CouldNotIntersectFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; value of the {1} enum does could not be inverted..
        /// </summary>
        internal static string ExtendedEnumGeneric_Invert_CouldNotInvertFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Invert_CouldNotInvertFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; value of the {1} enum could not be set with the value &apos;{2}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_Set_CouldNotSetFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Set_CouldNotSetFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not split flags &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_SplitFlags_CouldNotSplitFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_SplitFlags_CouldNotSplitFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is a flag enum..
        /// </summary>
        internal static string ExtendedEnumGeneric_TypeIsFlagEnum {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_TypeIsFlagEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not an enum..
        /// </summary>
        internal static string ExtendedEnumGeneric_TypeIsNotAnEnum {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_TypeIsNotAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not a flag enum..
        /// </summary>
        internal static string ExtendedEnumGeneric_TypeIsNotFlagEnum {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_TypeIsNotFlagEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast item at index {0} of Tuple from type {1} to type {2}..
        /// </summary>
        internal static string ExtendedTuple_CannotCastItemAtIndex {
            get {
                return ResourceManager.GetString("ExtendedTuple_CannotCastItemAtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuple &apos;{0}&apos; does not have a &apos;{1}&apos; property..
        /// </summary>
        internal static string ExtendedTuple_CouldNotFindProperty {
            get {
                return ResourceManager.GetString("ExtendedTuple_CouldNotFindProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuple &apos;{0}&apos; has more than 8 generic arguments, which is unsupported..
        /// </summary>
        internal static string ExtendedTuple_MoreThanEightGenericArguments {
            get {
                return ResourceManager.GetString("ExtendedTuple_MoreThanEightGenericArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not a valid tuple type..
        /// </summary>
        internal static string ExtendedTuple_TypeIsNotValidTuple {
            get {
                return ResourceManager.GetString("ExtendedTuple_TypeIsNotValidTuple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load embedded resource &apos;{0}&apos; from the &apos;{1}&apos; assembly..
        /// </summary>
        internal static string Extensions_EmbeddedXml_CouldntLoadEmbeddedResource {
            get {
                return ResourceManager.GetString("Extensions_EmbeddedXml_CouldntLoadEmbeddedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load embedded resource &apos;{0}&apos; from the &apos;{1}&apos; assembly. {2}.
        /// </summary>
        internal static string Extensions_EmbeddedXml_Exception {
            get {
                return ResourceManager.GetString("Extensions_EmbeddedXml_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency cycles found in enumeration, cannot sort topologically..
        /// </summary>
        internal static string Extensions_TopologicalSortEdges_DependencyCyclesFound {
            get {
                return ResourceManager.GetString("Extensions_TopologicalSortEdges_DependencyCyclesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency of the first operand &apos;{0}&apos; did not match that of the second &apos;{1}&apos; during an {2} operation..
        /// </summary>
        internal static string Financial_Currencies_Do_Not_Match {
            get {
                return ResourceManager.GetString("Financial_Currencies_Do_Not_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The financials argument contains no elements..
        /// </summary>
        internal static string Financial_Sum_EmptyEnumeration {
            get {
                return ResourceManager.GetString("Financial_Sum_EmptyEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currencies in the financial parameters must match..
        /// </summary>
        internal static string FinancialRange_CurrenciesMustMatch {
            get {
                return ResourceManager.GetString("FinancialRange_CurrenciesMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify a read only FormatBuilder..
        /// </summary>
        internal static string FormatBuilder_ReadOnly {
            get {
                return ResourceManager.GetString("FormatBuilder_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag cannot be null or empty.
        /// </summary>
        internal static string FormatBuilder_TagNullOrEmpty {
            get {
                return ResourceManager.GetString("FormatBuilder_TagNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to a closed FormatWriter..
        /// </summary>
        internal static string FormatWriter_IsClosed {
            get {
                return ResourceManager.GetString("FormatWriter_IsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username..
        /// </summary>
        internal static string Impersonator_Impersonator_InvalidUsername {
            get {
                return ResourceManager.GetString("Impersonator_Impersonator_InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberInfo not found in expression.
        /// </summary>
        internal static string InfoHelper_GetMemberInfoInternal_NotFound {
            get {
                return ResourceManager.GetString("InfoHelper_GetMemberInfoInternal_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found in expression.
        /// </summary>
        internal static string InfoHelper_GetMemberInfoInternal_T_NotFound {
            get {
                return ResourceManager.GetString("InfoHelper_GetMemberInfoInternal_T_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse the string &apos;{0}&apos; to an Instant..
        /// </summary>
        internal static string InstantConverter_ConvertFrom_CannotParse {
            get {
                return ResourceManager.GetString("InstantConverter_ConvertFrom_CannotParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum capacity is {0}..
        /// </summary>
        internal static string LimitedConcurrentQueue_LimitedConcurrentQueue_Maximum_Capacity {
            get {
                return ResourceManager.GetString("LimitedConcurrentQueue_LimitedConcurrentQueue_Maximum_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum capacity is 1..
        /// </summary>
        internal static string LimitedConcurrentQueue_LimitedConcurrentQueue_Minimum_Capacity {
            get {
                return ResourceManager.GetString("LimitedConcurrentQueue_LimitedConcurrentQueue_Minimum_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICollection.SyncRoot unsupported..
        /// </summary>
        internal static string LimitedConcurrentQueue_SyncRoot_ICollection_SyncRoot_Unsupported {
            get {
                return ResourceManager.GetString("LimitedConcurrentQueue_SyncRoot_ICollection_SyncRoot_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuple was null..
        /// </summary>
        internal static string List_Get_TupleNull {
            get {
                return ResourceManager.GetString("List_Get_TupleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration cannot have time component.
        /// </summary>
        internal static string LocalDateRange_DurationCannotHaveTime {
            get {
                return ResourceManager.GetString("LocalDateRange_DurationCannotHaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step cannot have time component.
        /// </summary>
        internal static string LocalDateRange_StepCannotHaveTime {
            get {
                return ResourceManager.GetString("LocalDateRange_StepCannotHaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse the string &apos;{0}&apos; to a LocalDateTime..
        /// </summary>
        internal static string LocalDateTimeConverter_ConvertFrom_CannotParse {
            get {
                return ResourceManager.GetString("LocalDateTimeConverter_ConvertFrom_CannotParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration must be positive.
        /// </summary>
        internal static string LocalRange_DurationMustBePositive {
            get {
                return ResourceManager.GetString("LocalRange_DurationMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step must be positive.
        /// </summary>
        internal static string LocalRange_StepMustBePositive {
            get {
                return ResourceManager.GetString("LocalRange_StepMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration cannot have date component.
        /// </summary>
        internal static string LocalTimeRange_DurationCannotHaveDate {
            get {
                return ResourceManager.GetString("LocalTimeRange_DurationCannotHaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step cannot have date component.
        /// </summary>
        internal static string LocalTimeRange_StepCannotHaveDate {
            get {
                return ResourceManager.GetString("LocalTimeRange_StepCannotHaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of parameter replacement expressions &apos;{0}&apos; does not match the number of parameters in the lambda expression &apos;{1}&apos;..
        /// </summary>
        internal static string ParameterReplacerVisitor_ExpressionCountMismatch {
            get {
                return ResourceManager.GetString("ParameterReplacerVisitor_ExpressionCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse the string &apos;{0}&apos; to a Period..
        /// </summary>
        internal static string PeriodConverter_ConvertFrom_CannotParse {
            get {
                return ResourceManager.GetString("PeriodConverter_ConvertFrom_CannotParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration system couldn&apos;t convert the value &apos;{0}&apos; for the parameter &apos;{1}&apos; to type &apos;{2}&apos;..
        /// </summary>
        internal static string PInfo_TypeProperty_CannotConvertValueStrToDestinationType {
            get {
                return ResourceManager.GetString("PInfo_TypeProperty_CannotConvertValueStrToDestinationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a default type converter for parameter &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        internal static string PInfo_TypeProperty_CannotCreateDefaultTypeConverter {
            get {
                return ResourceManager.GetString("PInfo_TypeProperty_CannotCreateDefaultTypeConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter of type &apos;{0}&apos; cannot convert from string for parameter &apos;{1}&apos;..
        /// </summary>
        internal static string PInfo_TypeProperty_ConverterCannotConvertFromString {
            get {
                return ResourceManager.GetString("PInfo_TypeProperty_ConverterCannotConvertFromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter of type &apos;{0}&apos; returned null value for parameter &apos;{1}&apos; which is of non-nullable type &apos;{2}&apos;..
        /// </summary>
        internal static string PInfo_TypeProperty_ConveterReturnedNullForNonNullableType {
            get {
                return ResourceManager.GetString("PInfo_TypeProperty_ConveterReturnedNullForNonNullableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter of type &apos;{0}&apos; returned value of type &apos;{1}&apos; for parameter &apos;{2}&apos; which is of type &apos;{3}&apos; and not assignable from type &apos;{1}&apos;..
        /// </summary>
        internal static string PInfo_TypeProperty_TypeNotAssignableFromConvertedType {
            get {
                return ResourceManager.GetString("PInfo_TypeProperty_TypeNotAssignableFromConvertedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value set for parameter &apos;{0}&apos;..
        /// </summary>
        internal static string PInfo_ValueProperty_NoValueSet {
            get {
                return ResourceManager.GetString("PInfo_ValueProperty_NoValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuple at the beginning of the queue was null..
        /// </summary>
        internal static string Queue_TupleNull {
            get {
                return ResourceManager.GetString("Queue_TupleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start &apos;{0}&apos; must not be greater than the end &apos;{1}&apos; for a range of &apos;{2}&apos;..
        /// </summary>
        internal static string Range_StartGreaterThanEnd {
            get {
                return ResourceManager.GetString("Range_StartGreaterThanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert the expression of type &apos;{0}&apos; to an expression of type &apos;{1}&apos;..
        /// </summary>
        internal static string Reflection_Convert_ConversionFailed {
            get {
                return ResourceManager.GetString("Reflection_Convert_ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function returned null.
        /// </summary>
        internal static string Reflection_ExpressionFunc_FunctionReturnedNull {
            get {
                return ResourceManager.GetString("Reflection_ExpressionFunc_FunctionReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda action from &apos;{0}&apos;, incorrect parameter count..
        /// </summary>
        internal static string Reflection_GetAction_IncorrectParameterCount {
            get {
                return ResourceManager.GetString("Reflection_GetAction_IncorrectParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda action from &apos;{0}&apos;, cannot assign type &apos;{1}&apos; to parameter of type &apos;{2}&apos;..
        /// </summary>
        internal static string Reflection_GetAction_ParameterNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetAction_ParameterNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, incorrect parameter count..
        /// </summary>
        internal static string Reflection_GetFunc_IncorrectParameterCount {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_IncorrectParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, as it is a method with no return type, use Action&lt;&gt;() instead..
        /// </summary>
        internal static string Reflection_GetFunc_MethodHasNoReturnType {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_MethodHasNoReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, as it is a static constructor..
        /// </summary>
        internal static string Reflection_GetFunc_MethodIsStaticConstructor {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_MethodIsStaticConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, no parameter/return types specified..
        /// </summary>
        internal static string Reflection_GetFunc_NoFuncTypesSpecified {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_NoFuncTypesSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, cannot assign type &apos;{1}&apos; to parameter of type &apos;{2}&apos;..
        /// </summary>
        internal static string Reflection_GetFunc_ParameterNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_ParameterNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, cannot assign return type {1} to {2}..
        /// </summary>
        internal static string Reflection_GetFunc_ReturnTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_ReturnTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be an interface.
        /// </summary>
        internal static string Reflection_ImplementsInterface_MustBeInterface {
            get {
                return ResourceManager.GetString("Reflection_ImplementsInterface_MustBeInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueFactory attempted to access the Value property of this instance..
        /// </summary>
        internal static string ResettableLazy_CreateValue_ValueFactoryAccessedValue {
            get {
                return ResourceManager.GetString("ResettableLazy_CreateValue_ValueFactoryAccessedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lazily-initialized type does not have a public, parameterless constructor..
        /// </summary>
        internal static string ResettableLazy_GetCtorFunc_NoDefaultCtor {
            get {
                return ResourceManager.GetString("ResettableLazy_GetCtorFunc_NoDefaultCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not created..
        /// </summary>
        internal static string ResettableLazy_ToString_ValueNotCreated {
            get {
                return ResourceManager.GetString("ResettableLazy_ToString_ValueNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified semantic version string was not valid..
        /// </summary>
        internal static string SemanticVersion_Parse_Invalid {
            get {
                return ResourceManager.GetString("SemanticVersion_Parse_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The build string contains invalid characters.
        /// </summary>
        internal static string SemanticVersion_SemanticVersion_BuildInvalid {
            get {
                return ResourceManager.GetString("SemanticVersion_SemanticVersion_BuildInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The major version number can not be negative..
        /// </summary>
        internal static string SemanticVersion_SemanticVersion_MajorNegative {
            get {
                return ResourceManager.GetString("SemanticVersion_SemanticVersion_MajorNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minor version number can not be negative..
        /// </summary>
        internal static string SemanticVersion_SemanticVersion_MinorNegative {
            get {
                return ResourceManager.GetString("SemanticVersion_SemanticVersion_MinorNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patch version number can not be negative..
        /// </summary>
        internal static string SemanticVersion_SemanticVersion_PatchNegative {
            get {
                return ResourceManager.GetString("SemanticVersion_SemanticVersion_PatchNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pre-release string contains invalid characters..
        /// </summary>
        internal static string SemanticVersion_SemanticVersion_PreReleaseInvalid {
            get {
                return ResourceManager.GetString("SemanticVersion_SemanticVersion_PreReleaseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; type was not found..
        /// </summary>
        internal static string SimplifiedTypeNameConverter_ConvertFrom_Unknown_Type {
            get {
                return ResourceManager.GetString("SimplifiedTypeNameConverter_ConvertFrom_Unknown_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified value must be a type..
        /// </summary>
        internal static string SimplifiedTypeNameConverter_ConvertTo_Invalid_Type {
            get {
                return ResourceManager.GetString("SimplifiedTypeNameConverter_ConvertTo_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuple at the top of the stack was null..
        /// </summary>
        internal static string Stack_TupleNull {
            get {
                return ResourceManager.GetString("Stack_TupleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antecedent task was cancelled..
        /// </summary>
        internal static string TaskExtensions_After_AntecedentTaskCancelled {
            get {
                return ResourceManager.GetString("TaskExtensions_After_AntecedentTaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antecedent task was in faulted state, without an error..
        /// </summary>
        internal static string TaskExtensions_After_AntecedentTaskInFaultedState {
            get {
                return ResourceManager.GetString("TaskExtensions_After_AntecedentTaskInFaultedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The antecedent task was not in a valid state..
        /// </summary>
        internal static string TaskExtensions_After_AntecedentTaskInvalidState {
            get {
                return ResourceManager.GetString("TaskExtensions_After_AntecedentTaskInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An antecedent task was cancelled..
        /// </summary>
        internal static string TaskExtensions_AfterAll_AntecedentTaskCancelled {
            get {
                return ResourceManager.GetString("TaskExtensions_AfterAll_AntecedentTaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antecedent task was in faulted state, without an error..
        /// </summary>
        internal static string TaskExtensions_AfterAll_AntecedentTaskInFaultedState {
            get {
                return ResourceManager.GetString("TaskExtensions_AfterAll_AntecedentTaskInFaultedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The antecedent task was not in a valid state..
        /// </summary>
        internal static string TaskExtensions_AfterAll_AntecedentTaskInvalidState {
            get {
                return ResourceManager.GetString("TaskExtensions_AfterAll_AntecedentTaskInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task was in a faulted state, but no exceptions were available..
        /// </summary>
        internal static string TaskExtensions_SetFromTask_TaskStateFaulted {
            get {
                return ResourceManager.GetString("TaskExtensions_SetFromTask_TaskStateFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task was not completed..
        /// </summary>
        internal static string TaskExtensions_SetFromTask_TaskWasNotCompleted {
            get {
                return ResourceManager.GetString("TaskExtensions_SetFromTask_TaskWasNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal exception occurred whilst trying to load the TimeZone DB &apos;{0}..
        /// </summary>
        internal static string TimeHelper_TimeHelper_TimeZoneDB_Failed {
            get {
                return ResourceManager.GetString("TimeHelper_TimeHelper_TimeZoneDB_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path to the time zone database &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string TimeHelper_TimeHelper_TimeZoneDB_Not_Found {
            get {
                return ResourceManager.GetString("TimeHelper_TimeHelper_TimeZoneDB_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delta must be greater than or equal to zero..
        /// </summary>
        internal static string TimeSpanRange_AutoStep_DeltaNegative {
            get {
                return ResourceManager.GetString("TimeSpanRange_AutoStep_DeltaNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast an unknown TriState to a Boolean.
        /// </summary>
        internal static string TriState_ExplicitBoolConversion_CannotCastUnknownState {
            get {
                return ResourceManager.GetString("TriState_ExplicitBoolConversion_CannotCastUnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast byte &apos;{0}&apos; to TriState, value must be less than 3..
        /// </summary>
        internal static string TriState_ExplicitByteConversion_ValueGreaterThanThree {
            get {
                return ResourceManager.GetString("TriState_ExplicitByteConversion_ValueGreaterThanThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} format string is not supported..
        /// </summary>
        internal static string TriState_ToString_FormatException {
            get {
                return ResourceManager.GetString("TriState_ToString_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source must not be empty.
        /// </summary>
        internal static string UtilityExtensions_SourceEmpty {
            get {
                return ResourceManager.GetString("UtilityExtensions_SourceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value is greater than the maximum value..
        /// </summary>
        internal static string Validator_MinGreaterThanMax {
            get {
                return ResourceManager.GetString("Validator_MinGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not in the range &apos;{1} to {2}&apos;..
        /// </summary>
        internal static string Validator_Validate_ValueNotInRange {
            get {
                return ResourceManager.GetString("Validator_Validate_ValueNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not outside the range &apos;{1} to {2}&apos;..
        /// </summary>
        internal static string Validator_Validate_ValueNotOutsideRange {
            get {
                return ResourceManager.GetString("Validator_Validate_ValueNotOutsideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not of the correct type..
        /// </summary>
        internal static string Validator_Validate_WrongType {
            get {
                return ResourceManager.GetString("Validator_Validate_WrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoding was invalid, ran out of bytes before getting an end of encoding byte..
        /// </summary>
        internal static string VariableLengthEncoding_Decode_Buffer_Overflow {
            get {
                return ResourceManager.GetString("VariableLengthEncoding_Decode_Buffer_Overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not encode the value as the buffer ran out of space..
        /// </summary>
        internal static string VariableLengthEncoding_Encode_Buffer_Overflow {
            get {
                return ResourceManager.GetString("VariableLengthEncoding_Encode_Buffer_Overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key already exists..
        /// </summary>
        internal static string WeakConcurrentDictionary_Add_KeyAlreadyExists {
            get {
                return ResourceManager.GetString("WeakConcurrentDictionary_Add_KeyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of key is incorrect..
        /// </summary>
        internal static string WeakConcurrentDictionary_Add_KeyTypeIncorrect {
            get {
                return ResourceManager.GetString("WeakConcurrentDictionary_Add_KeyTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of value is incorrect.
        /// </summary>
        internal static string WeakConcurrentDictionary_Add_ValueTypeIncorrect {
            get {
                return ResourceManager.GetString("WeakConcurrentDictionary_Add_ValueTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array type..
        /// </summary>
        internal static string WeakConcurrentDictionary_CopyTo_InvalidArrayType {
            get {
                return ResourceManager.GetString("WeakConcurrentDictionary_CopyTo_InvalidArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key cannot be null..
        /// </summary>
        internal static string WeakConcurrentDictionary_KeyIsNull {
            get {
                return ResourceManager.GetString("WeakConcurrentDictionary_KeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element name &apos;{0}&apos; does not match the specified element name &apos;{1}&apos;..
        /// </summary>
        internal static string XmlConfigurationSection_SetElement_Element_Name_Mismatch {
            get {
                return ResourceManager.GetString("XmlConfigurationSection_SetElement_Element_Name_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration element&apos;s child element cannot be modified as the configuration element is read only..
        /// </summary>
        internal static string XmlConfigurationSection_SetElement_ReadOnly {
            get {
                return ResourceManager.GetString("XmlConfigurationSection_SetElement_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse the string &apos;{0}&apos; to a ZonedDateTime..
        /// </summary>
        internal static string ZonedDateTimeConverter_ConvertFrom_CannotParse {
            get {
                return ResourceManager.GetString("ZonedDateTimeConverter_ConvertFrom_CannotParse", resourceCulture);
            }
        }
    }
}
