//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplications.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplications.Utilities.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set a result only once.
        /// </summary>
        internal static string AsyncResult_SetAsCompleted_CanOnlySetResultOnce {
            get {
                return ResourceManager.GetString("AsyncResult_SetAsCompleted_CanOnlySetResultOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache expiry must be at least 1s..
        /// </summary>
        internal static string CachingQueue_ExpiryTooShort {
            get {
                return ResourceManager.GetString("CachingQueue_ExpiryTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum entries must be at least 1..
        /// </summary>
        internal static string CachingQueue_MaxEntriesLessThanOne {
            get {
                return ResourceManager.GetString("CachingQueue_MaxEntriesLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date time supplied to a CombGuid cannot be before &apos;{0}&apos; UTC..
        /// </summary>
        internal static string CombGuid_InvalidDateTime_TooEarly {
            get {
                return ResourceManager.GetString("CombGuid_InvalidDateTime_TooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set a configuration element collection using a key &apos;{0}&apos; that does not match the configuration element&apos;s key &apos;{1}&apos;..
        /// </summary>
        internal static string ConfigurationElementCollection_SetElement_KeyMismatch {
            get {
                return ResourceManager.GetString("ConfigurationElementCollection_SetElement_KeyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration system could not find a constructor with the relevant parameters when trying to create an object of type &apos;{0}&apos;..
        /// </summary>
        internal static string ConstructorConfigurationElement_GetConstructor_CannotFindConstructor {
            get {
                return ResourceManager.GetString("ConstructorConfigurationElement_GetConstructor_CannotFindConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration system found a number of potential constructor matches when trying to create an object of type &apos;{0}&apos;..
        /// </summary>
        internal static string ConstructorConfigurationElement_GetConstructor_ConstructorIsAmbiguous {
            get {
                return ResourceManager.GetString("ConstructorConfigurationElement_GetConstructor_ConstructorIsAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration system cannot assign the created type &apos;{0}&apos; to the required type &apos;{1}&apos;..
        /// </summary>
        internal static string ConstructorConfigurationElement_GetConstructor_CreatedTypeNotAssignable {
            get {
                return ResourceManager.GetString("ConstructorConfigurationElement_GetConstructor_CreatedTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot close the ContextStack cleaner region on thread &apos;{0}&apos; as it was created on thread &apos;{1}&apos;..
        /// </summary>
        internal static string ContextStack_Dispose_CannotCloseCleanerRegion {
            get {
                return ResourceManager.GetString("ContextStack_Dispose_CannotCloseCleanerRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot close the ContextStack region on thread &apos;{0}&apos; as it was created on thread &apos;{1}&apos;..
        /// </summary>
        internal static string ContextStack_Dispose_CannotCloseRegion {
            get {
                return ResourceManager.GetString("ContextStack_Dispose_CannotCloseRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;cultureInfo&apos; can not be null.
        /// </summary>
        internal static string CultureHelper_CultureInfoCannotBeNull {
            get {
                return ResourceManager.GetString("CultureHelper_CultureInfoCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;currencyISO&apos; can not be null.
        /// </summary>
        internal static string CultureHelper_CurrencyIsoCannotBeNull {
            get {
                return ResourceManager.GetString("CultureHelper_CurrencyIsoCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;isoCode&apos; can not be null.
        /// </summary>
        internal static string CultureHelper_IsoCodeCannotBeNull {
            get {
                return ResourceManager.GetString("CultureHelper_IsoCodeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;name&apos; can not be null.
        /// </summary>
        internal static string CultureHelper_NameCannotBeNull {
            get {
                return ResourceManager.GetString("CultureHelper_NameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;regionInfo&apos; can not be null.
        /// </summary>
        internal static string CultureHelper_RegionInfoCannotBeNull {
            get {
                return ResourceManager.GetString("CultureHelper_RegionInfoCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;cultureInfo&apos; can not be null.
        /// </summary>
        internal static string CurrencyInfo_CultureInfoCannotBeNull {
            get {
                return ResourceManager.GetString("CurrencyInfo_CultureInfoCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;currencyCode&apos; can not be null.
        /// </summary>
        internal static string CurrencyInfo_CurrencyCodeCannotBeNull {
            get {
                return ResourceManager.GetString("CurrencyInfo_CurrencyCodeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;regionInfo&apos; can not be null.
        /// </summary>
        internal static string CurrencyInfo_RegionInfoCannotBeNull {
            get {
                return ResourceManager.GetString("CurrencyInfo_RegionInfoCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency: {0}, Code: {1}, ISO: {2}.
        /// </summary>
        internal static string CurrencyInfo_ToString {
            get {
                return ResourceManager.GetString("CurrencyInfo_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} completed in {1}ms..
        /// </summary>
        internal static string DebuggingExtensions_Stopwatch_ToString {
            get {
                return ResourceManager.GetString("DebuggingExtensions_Stopwatch_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot safely flush the default enhanced memory cache..
        /// </summary>
        internal static string EnhancedMemoryCache_Clear_CannotSafelyFlush {
            get {
                return ResourceManager.GetString("EnhancedMemoryCache_Clear_CannotSafelyFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; value of the {1} enum does could not be cleared with the value &apos;{2}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_Clear_CouldNotClearFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Clear_CouldNotClearFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not combine flags of type &apos;{0}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_Combine_CouldNotCombineFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Combine_CouldNotCombineFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} enum does not contain the name &apos;{1}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_DoesNotContainName {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_DoesNotContainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} enum does not contain the raw value &apos;{1}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_DoesNotContainRawValue {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_DoesNotContainRawValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} enum does not contain the value &apos;{1}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_DoesNotContainValue {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_DoesNotContainValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; value of the {1} enum does could not be intersected with the value &apos;{2}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_Intersect_CouldNotIntersectFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Intersect_CouldNotIntersectFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; value of the {1} enum does could not be inverted..
        /// </summary>
        internal static string ExtendedEnumGeneric_Invert_CouldNotInvertFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Invert_CouldNotInvertFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; value of the {1} enum could not be set with the value &apos;{2}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_Set_CouldNotSetFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Set_CouldNotSetFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not split flags &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_SplitFlags_CouldNotSplitFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_SplitFlags_CouldNotSplitFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is a flag enum..
        /// </summary>
        internal static string ExtendedEnumGeneric_TypeIsFlagEnum {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_TypeIsFlagEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not an enum..
        /// </summary>
        internal static string ExtendedEnumGeneric_TypeIsNotAnEnum {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_TypeIsNotAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not a flag enum..
        /// </summary>
        internal static string ExtendedEnumGeneric_TypeIsNotFlagEnum {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_TypeIsNotFlagEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast item at index {0} of Tuple from type {1} to type {2}..
        /// </summary>
        internal static string ExtendedTuple_CannotCastItemAtIndex {
            get {
                return ResourceManager.GetString("ExtendedTuple_CannotCastItemAtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuple &apos;{0}&apos; does not have a &apos;{1}&apos; property..
        /// </summary>
        internal static string ExtendedTuple_CouldNotFindProperty {
            get {
                return ResourceManager.GetString("ExtendedTuple_CouldNotFindProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuple &apos;{0}&apos; has more than 8 generic arguments, which is unsupported..
        /// </summary>
        internal static string ExtendedTuple_MoreThanEightGenericArguments {
            get {
                return ResourceManager.GetString("ExtendedTuple_MoreThanEightGenericArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not a valid tuple type..
        /// </summary>
        internal static string ExtendedTuple_TypeIsNotValidTuple {
            get {
                return ResourceManager.GetString("ExtendedTuple_TypeIsNotValidTuple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load embedded resource &apos;{0}&apos; from the &apos;{1}&apos; assembly..
        /// </summary>
        internal static string Extensions_EmbeddedXml_CouldntLoadEmbeddedResource {
            get {
                return ResourceManager.GetString("Extensions_EmbeddedXml_CouldntLoadEmbeddedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load embedded resource &apos;{0}&apos; from the &apos;{1}&apos; assembly. {2}.
        /// </summary>
        internal static string Extensions_EmbeddedXml_Exception {
            get {
                return ResourceManager.GetString("Extensions_EmbeddedXml_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency cycles found in enumeration, cannot sort topologically..
        /// </summary>
        internal static string Extensions_TopologicalSortEdges_DependencyCyclesFound {
            get {
                return ResourceManager.GetString("Extensions_TopologicalSortEdges_DependencyCyclesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency of the first operand &apos;{0}&apos; did not match that of the second &apos;{1}&apos; during an {2} operation..
        /// </summary>
        internal static string Financial_Currencies_Do_Not_Match {
            get {
                return ResourceManager.GetString("Financial_Currencies_Do_Not_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The financials argument contains no elements..
        /// </summary>
        internal static string Financial_Sum_EmptyEnumeration {
            get {
                return ResourceManager.GetString("Financial_Sum_EmptyEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to a closed FormatWriter..
        /// </summary>
        internal static string FormatWriter_IsClosed {
            get {
                return ResourceManager.GetString("FormatWriter_IsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum capacity is {0}..
        /// </summary>
        internal static string LimitedConcurrentQueue_LimitedConcurrentQueue_Maximum_Capacity {
            get {
                return ResourceManager.GetString("LimitedConcurrentQueue_LimitedConcurrentQueue_Maximum_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum capacity is 1..
        /// </summary>
        internal static string LimitedConcurrentQueue_LimitedConcurrentQueue_Minimum_Capacity {
            get {
                return ResourceManager.GetString("LimitedConcurrentQueue_LimitedConcurrentQueue_Minimum_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICollection.SyncRoot unsupported..
        /// </summary>
        internal static string LimitedConcurrentQueue_SyncRoot_ICollection_SyncRoot_Unsupported {
            get {
                return ResourceManager.GetString("LimitedConcurrentQueue_SyncRoot_ICollection_SyncRoot_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration system couldn&apos;t convert the value &apos;{0}&apos; for the parameter &apos;{1}&apos; to type &apos;{2}&apos;..
        /// </summary>
        internal static string PInfo_TypeProperty_CannotConvertValueStrToDestinationType {
            get {
                return ResourceManager.GetString("PInfo_TypeProperty_CannotConvertValueStrToDestinationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a default type converter for parameter &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        internal static string PInfo_TypeProperty_CannotCreateDefaultTypeConverter {
            get {
                return ResourceManager.GetString("PInfo_TypeProperty_CannotCreateDefaultTypeConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter of type &apos;{0}&apos; cannot convert from string for parameter &apos;{1}&apos;..
        /// </summary>
        internal static string PInfo_TypeProperty_ConverterCannotConvertFromString {
            get {
                return ResourceManager.GetString("PInfo_TypeProperty_ConverterCannotConvertFromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter of type &apos;{0}&apos; returned null value for parameter &apos;{1}&apos; which is of non-nullable type &apos;{2}&apos;..
        /// </summary>
        internal static string PInfo_TypeProperty_ConveterReturnedNullForNonNullableType {
            get {
                return ResourceManager.GetString("PInfo_TypeProperty_ConveterReturnedNullForNonNullableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter of type &apos;{0}&apos; returned value of type &apos;{1}&apos; for parameter &apos;{2}&apos; which is of type &apos;{3}&apos; and not assignable from type &apos;{1}&apos;..
        /// </summary>
        internal static string PInfo_TypeProperty_TypeNotAssignableFromConvertedType {
            get {
                return ResourceManager.GetString("PInfo_TypeProperty_TypeNotAssignableFromConvertedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value set for parameter &apos;{0}&apos;..
        /// </summary>
        internal static string PInfo_ValueProperty_NoValueSet {
            get {
                return ResourceManager.GetString("PInfo_ValueProperty_NoValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start &apos;{0}&apos; must not be greater than the end &apos;{1}&apos; for a range of &apos;{2}&apos;..
        /// </summary>
        internal static string Range_StartGreaterThanEnd {
            get {
                return ResourceManager.GetString("Range_StartGreaterThanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert the expression of type &apos;{0}&apos; to an expression of type &apos;{1}&apos;..
        /// </summary>
        internal static string Reflection_Convert_ConversionFailed {
            get {
                return ResourceManager.GetString("Reflection_Convert_ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda action from &apos;{0}&apos;, incorrect parameter count..
        /// </summary>
        internal static string Reflection_GetAction_IncorrectParameterCount {
            get {
                return ResourceManager.GetString("Reflection_GetAction_IncorrectParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda action from &apos;{0}&apos;, cannot assign type &apos;{1}&apos; to parameter of type &apos;{2}&apos;..
        /// </summary>
        internal static string Reflection_GetAction_ParameterNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetAction_ParameterNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, incorrect parameter count..
        /// </summary>
        internal static string Reflection_GetFunc_IncorrectParameterCount {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_IncorrectParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, as it is a method with no return type, use Action&lt;&gt;() instead..
        /// </summary>
        internal static string Reflection_GetFunc_MethodHasNoReturnType {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_MethodHasNoReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, as it is a static constructor..
        /// </summary>
        internal static string Reflection_GetFunc_MethodIsStaticConstructor {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_MethodIsStaticConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, no parameter/return types specified..
        /// </summary>
        internal static string Reflection_GetFunc_NoFuncTypesSpecified {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_NoFuncTypesSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, cannot assign type &apos;{1}&apos; to parameter of type &apos;{2}&apos;..
        /// </summary>
        internal static string Reflection_GetFunc_ParameterNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_ParameterNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, cannot assign return type {1} to {2}..
        /// </summary>
        internal static string Reflection_GetFunc_ReturnTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_ReturnTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; getter on the type &apos;{1}&apos; as the name does not correspond to a field or property with a get accessor..
        /// </summary>
        internal static string Reflection_GetGetter_NoGetterForFieldOrProperty {
            get {
                return ResourceManager.GetString("Reflection_GetGetter_NoGetterForFieldOrProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} getter on the type &apos;{2}&apos; as the parameter type &apos;{3}&apos; is not assignable from the &apos;{2}&apos; declaring type..
        /// </summary>
        internal static string Reflection_GetGetter_ParameterTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetGetter_ParameterTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} getter on the type &apos;{2}&apos; as the {1} type &apos;{3}&apos; is not assignable to the &apos;{4}&apos; return type..
        /// </summary>
        internal static string Reflection_GetGetter_ReturnTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetGetter_ReturnTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} setter on the type &apos;{2}&apos; as the {1} type &apos;{3}&apos; is not assignable from the &apos;{4}&apos; value type..
        /// </summary>
        internal static string Reflection_GetSetter_MemberTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetSetter_MemberTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; setter on the type &apos;{1}&apos; as the name does not correspond to a field or property with a set accessor..
        /// </summary>
        internal static string Reflection_GetSetter_NoSetterForFieldOrProperty {
            get {
                return ResourceManager.GetString("Reflection_GetSetter_NoSetterForFieldOrProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} setter on the type &apos;{2}&apos; as the parameter type &apos;{3}&apos; is not assignable from the &apos;{2}&apos; declaring type..
        /// </summary>
        internal static string Reflection_GetSetter_ParameterTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetSetter_ParameterTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} setter on the type &apos;{2}&apos; as the {1} type &apos;{3}&apos; is not assignable to the &apos;{4}&apos; return type..
        /// </summary>
        internal static string Reflection_GetSetter_ReturnTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetSetter_ReturnTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; getter on the type &apos;{1}&apos; as the name does not correspond to a field or property with a get accessor..
        /// </summary>
        internal static string Reflector_GetGetter_DoesNotHaveGetter {
            get {
                return ResourceManager.GetString("Reflector_GetGetter_DoesNotHaveGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; does not exist on the type &apos;{1}&apos;..
        /// </summary>
        internal static string Reflector_GetGetter_MemberDoesNotExist {
            get {
                return ResourceManager.GetString("Reflector_GetGetter_MemberDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} getter on the type &apos;{2}&apos; as the parameter type &apos;{3}&apos; is not assignable from the &apos;{2}&apos; declaring type..
        /// </summary>
        internal static string Reflector_GetGetter_ParameterTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflector_GetGetter_ParameterTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} getter on the type &apos;{2}&apos; as the {1} type &apos;{3}&apos; is not assignable to the &apos;{4}&apos; return type..
        /// </summary>
        internal static string Reflector_GetGetter_ReturnTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflector_GetGetter_ReturnTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The surrogateType must be a concrete type and not an interface..
        /// </summary>
        internal static string Serialize_AddOrUpdateSurrogate_MustBeConcrete {
            get {
                return ResourceManager.GetString("Serialize_AddOrUpdateSurrogate_MustBeConcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The surrogateType must implement ISerializationSurrogate..
        /// </summary>
        internal static string Serialize_AddOrUpdateSurrogate_MustImplementISerializationSurrogate {
            get {
                return ResourceManager.GetString("Serialize_AddOrUpdateSurrogate_MustImplementISerializationSurrogate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antecedent task was cancelled..
        /// </summary>
        internal static string TaskExtensions_After_AntecedentTaskCancelled {
            get {
                return ResourceManager.GetString("TaskExtensions_After_AntecedentTaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antecedent task was in faulted state, without an error..
        /// </summary>
        internal static string TaskExtensions_After_AntecedentTaskInFaultedState {
            get {
                return ResourceManager.GetString("TaskExtensions_After_AntecedentTaskInFaultedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The antecedent task was not in a valid state..
        /// </summary>
        internal static string TaskExtensions_After_AntecedentTaskInvalidState {
            get {
                return ResourceManager.GetString("TaskExtensions_After_AntecedentTaskInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An antecedent task was cancelled..
        /// </summary>
        internal static string TaskExtensions_AfterAll_AntecedentTaskCancelled {
            get {
                return ResourceManager.GetString("TaskExtensions_AfterAll_AntecedentTaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antecedent task was in faulted state, without an error..
        /// </summary>
        internal static string TaskExtensions_AfterAll_AntecedentTaskInFaultedState {
            get {
                return ResourceManager.GetString("TaskExtensions_AfterAll_AntecedentTaskInFaultedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The antecedent task was not in a valid state..
        /// </summary>
        internal static string TaskExtensions_AfterAll_AntecedentTaskInvalidState {
            get {
                return ResourceManager.GetString("TaskExtensions_AfterAll_AntecedentTaskInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task was in a faulted state, but no exceptions were available..
        /// </summary>
        internal static string TaskExtensions_SetFromTask_TaskStateFaulted {
            get {
                return ResourceManager.GetString("TaskExtensions_SetFromTask_TaskStateFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task was not completed..
        /// </summary>
        internal static string TaskExtensions_SetFromTask_TaskWasNotCompleted {
            get {
                return ResourceManager.GetString("TaskExtensions_SetFromTask_TaskWasNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast an unknown TriState to a Boolean.
        /// </summary>
        internal static string TriState_ExplicitBoolConversion_CannotCastUnknownState {
            get {
                return ResourceManager.GetString("TriState_ExplicitBoolConversion_CannotCastUnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast byte &apos;{0}&apos; to TriState, value must be less than 3..
        /// </summary>
        internal static string TriState_ExplicitByteConversion_ValueGreaterThanThree {
            get {
                return ResourceManager.GetString("TriState_ExplicitByteConversion_ValueGreaterThanThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} format string is not supported..
        /// </summary>
        internal static string TriState_ToString_FormatException {
            get {
                return ResourceManager.GetString("TriState_ToString_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key already exists..
        /// </summary>
        internal static string WeakConcurrentDictionary_Add_KeyAlreadyExists {
            get {
                return ResourceManager.GetString("WeakConcurrentDictionary_Add_KeyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of key is incorrect..
        /// </summary>
        internal static string WeakConcurrentDictionary_Add_KeyTypeIncorrect {
            get {
                return ResourceManager.GetString("WeakConcurrentDictionary_Add_KeyTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of value is incorrect.
        /// </summary>
        internal static string WeakConcurrentDictionary_Add_ValueTypeIncorrect {
            get {
                return ResourceManager.GetString("WeakConcurrentDictionary_Add_ValueTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array type..
        /// </summary>
        internal static string WeakConcurrentDictionary_CopyTo_InvalidArrayType {
            get {
                return ResourceManager.GetString("WeakConcurrentDictionary_CopyTo_InvalidArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key cannot be null..
        /// </summary>
        internal static string WeakConcurrentDictionary_KeyIsNull {
            get {
                return ResourceManager.GetString("WeakConcurrentDictionary_KeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not serializable : {0}..
        /// </summary>
        internal static string XmlFormatter_GetMemberInfo_TypeNotSerializable {
            get {
                return ResourceManager.GetString("XmlFormatter_GetMemberInfo_TypeNotSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member cannot be serialized. {0}.
        /// </summary>
        internal static string XmlFormatter_GetMemberValue_MemberCannotBeSerialized {
            get {
                return ResourceManager.GetString("XmlFormatter_GetMemberValue_MemberCannotBeSerialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization stream contained element not found in type. {0}.
        /// </summary>
        internal static string XmlFormatter_InitializeObject_ElementNotFound {
            get {
                return ResourceManager.GetString("XmlFormatter_InitializeObject_ElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List in object is null. {0}, member {1}.
        /// </summary>
        internal static string XmlFormatter_InitializeObject_MemberListIsNull {
            get {
                return ResourceManager.GetString("XmlFormatter_InitializeObject_MemberListIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one member found for tag {0}.
        /// </summary>
        internal static string XmlFormatter_InitializeObject_MoreThanOneMemberFound {
            get {
                return ResourceManager.GetString("XmlFormatter_InitializeObject_MoreThanOneMemberFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty serializationStream!.
        /// </summary>
        internal static string XmlFormatter_Serialize_EmptyStream {
            get {
                return ResourceManager.GetString("XmlFormatter_Serialize_EmptyStream", resourceCulture);
            }
        }
    }
}
