//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplications.Utilities.Logging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplications.Utilities.Logging.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;eventLog&apos; can not be null.
        /// </summary>
        internal static string EventLogger_EventLogCannotBeNull {
            get {
                return ResourceManager.GetString("EventLogger_EventLogCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;log&apos; can not be null.
        /// </summary>
        internal static string EventLogger_LogCannotBeNull {
            get {
                return ResourceManager.GetString("EventLogger_LogCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;name&apos; can not be null.
        /// </summary>
        internal static string EventLogger_NameCannotBeNull {
            get {
                return ResourceManager.GetString("EventLogger_NameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create file logger as error occurred when trying to create/access directory &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string FileLogger_DirectoryAccessOrCreationError {
            get {
                return ResourceManager.GetString("FileLogger_DirectoryAccessOrCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create file logger as directory not specified..
        /// </summary>
        internal static string FileLogger_DirectoryNotSpecified {
            get {
                return ResourceManager.GetString("FileLogger_DirectoryNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create file logger as extension &apos;{0}&apos; has more than five characters..
        /// </summary>
        internal static string FileLogger_ExtensionLongerThanFiveCharacters {
            get {
                return ResourceManager.GetString("FileLogger_ExtensionLongerThanFiveCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create file logger as maximum log file duration &apos;{0}&apos; was less than 10s, which would cause too many log files to be created..
        /// </summary>
        internal static string FileLogger_FileDurationLessThanTenSeconds {
            get {
                return ResourceManager.GetString("FileLogger_FileDurationLessThanTenSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create file logger as file name format &apos;{0}&apos; contains invalid characters..
        /// </summary>
        internal static string FileLogger_FileNameFormatInvalid {
            get {
                return ResourceManager.GetString("FileLogger_FileNameFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create file logger as file name format not specified..
        /// </summary>
        internal static string FileLogger_FileNameFormatNotSpecified {
            get {
                return ResourceManager.GetString("FileLogger_FileNameFormatNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create file logger as file name format &apos;{0}&apos; led to invalid path creation. {1}.
        /// </summary>
        internal static string FileLogger_InvalidPathCreation {
            get {
                return ResourceManager.GetString("FileLogger_InvalidPathCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create file logger as maximum logs per file &apos;{0}&apos; was less than 10, which would cause too many log files to be created..
        /// </summary>
        internal static string FileLogger_MaximumLogsLessThanTen {
            get {
                return ResourceManager.GetString("FileLogger_MaximumLogsLessThanTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create file logger as file name format &apos;{0}&apos; led to invalid path creation. The file cannot be created outside the specified directory..
        /// </summary>
        internal static string FileLogger_PathCreatedOutsideDirectory {
            get {
                return ResourceManager.GetString("FileLogger_PathCreatedOutsideDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was not re-linked correctly..
        /// </summary>
        internal static string Log_Operation_OperationNotReLinked {
            get {
                return ResourceManager.GetString("Log_Operation_OperationNotReLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{0}Procedure: {2}, Line: {3}..
        /// </summary>
        internal static string Log_SqlException {
            get {
                return ResourceManager.GetString("Log_SqlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log{0}==={0}{1}ID: {2}{0}{1}Thread: {3} - {4}{0}{1}Group: {5}{0}{1}Time: {6:o}{0}{1}Level: {7}{0}{1}Message: {8}{0}{1}Operation: {9}{0}{1}Context: {10}{0}{11}.
        /// </summary>
        internal static string Log_ToString {
            get {
                return ResourceManager.GetString("Log_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Exception Type: {2}{0}{1}Stack Trace: {3}{0}.
        /// </summary>
        internal static string Log_ToString_LogException {
            get {
                return ResourceManager.GetString("Log_ToString_LogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} entr{1}).
        /// </summary>
        internal static string LogContext_ToString {
            get {
                return ResourceManager.GetString("LogContext_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} logger does not support log retrieval..
        /// </summary>
        internal static string LoggerBase_DoesNotSupportRetrieval {
            get {
                return ResourceManager.GetString("LoggerBase_DoesNotSupportRetrieval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} logger has not yet implemented the Get(endDate, limit) method..
        /// </summary>
        internal static string LoggerBase_GetEndDateLimit_NotImplemented {
            get {
                return ResourceManager.GetString("LoggerBase_GetEndDateLimit_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} logger has not yet implemented the Get(endDate, startDate) method..
        /// </summary>
        internal static string LoggerBase_GetEndDateStartDate_NotImplemented {
            get {
                return ResourceManager.GetString("LoggerBase_GetEndDateStartDate_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} logger has not yet implemented the Get(startDate, limit) method..
        /// </summary>
        internal static string LoggerBase_GetForwardStartDateLimit_NotImplemented {
            get {
                return ResourceManager.GetString("LoggerBase_GetForwardStartDateLimit_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;context&apos; can not be null.
        /// </summary>
        internal static string LoggingException_ContextCannotBeNull {
            get {
                return ResourceManager.GetString("LoggingException_ContextCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;innerException&apos; can not be null.
        /// </summary>
        internal static string LoggingException_InnerExceptionCannotBeNull {
            get {
                return ResourceManager.GetString("LoggingException_InnerExceptionCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;message&apos; can not be null.
        /// </summary>
        internal static string LoggingException_MessageCannotBeNull {
            get {
                return ResourceManager.GetString("LoggingException_MessageCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;parameters&apos; can not be null.
        /// </summary>
        internal static string LoggingException_ParametersCannotBeNull {
            get {
                return ResourceManager.GetString("LoggingException_ParametersCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not copy logs over from {0} logger as log retrieval is not supported!.
        /// </summary>
        internal static string LogStatic_AddOrUpdateLogger_RetrievalNotSupported {
            get {
                return ResourceManager.GetString("LogStatic_AddOrUpdateLogger_RetrievalNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve logs, limit is not greater than zero!.
        /// </summary>
        internal static string LogStatic_Get_LimitLessThanZero {
            get {
                return ResourceManager.GetString("LogStatic_Get_LimitLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No log cache available..
        /// </summary>
        internal static string LogStatic_Get_NoLogCacheAvailable {
            get {
                return ResourceManager.GetString("LogStatic_Get_NoLogCacheAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} logger does not support log retrieval..
        /// </summary>
        internal static string LogStatic_Get_RetrievalNotSupported {
            get {
                return ResourceManager.GetString("LogStatic_Get_RetrievalNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve logs, start date is greater or equal than current date!.
        /// </summary>
        internal static string LogStatic_Get_StartGreaterThanOrEqualToCurrent {
            get {
                return ResourceManager.GetString("LogStatic_Get_StartGreaterThanOrEqualToCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve logs, start date is greater or equal to end date!.
        /// </summary>
        internal static string LogStatic_Get_StartGreaterThanOrEqualToEnd {
            get {
                return ResourceManager.GetString("LogStatic_Get_StartGreaterThanOrEqualToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string LogStatic_GetLog_OperationCouldNotBeFound {
            get {
                return ResourceManager.GetString("LogStatic_GetLog_OperationCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred whilst creating logger &apos;{0}&apos; as specified in configuration file. {1}.
        /// </summary>
        internal static string LogStatic_LoadConfiguration_ErrorCreatingLogger {
            get {
                return ResourceManager.GetString("LogStatic_LoadConfiguration_ErrorCreatingLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error occurred whilst running the &apos;{0}&apos; logger, disabling - {1}.
        /// </summary>
        internal static string LogStatic_LogBatch_FatalErrorOccured {
            get {
                return ResourceManager.GetString("LogStatic_LogBatch_FatalErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error whilst logging - aborting..
        /// </summary>
        internal static string LogStatic_LoggerThread_FatalErrorWhilstLogging {
            get {
                return ResourceManager.GetString("LogStatic_LoggerThread_FatalErrorWhilstLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging thread was aborted..
        /// </summary>
        internal static string LogStatic_LoggerThread_LoggingThreadWasAborted {
            get {
                return ResourceManager.GetString("LogStatic_LoggerThread_LoggingThreadWasAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create memory logger as cache expiry &apos;{0}&apos; was less than 10s..
        /// </summary>
        internal static string MemoryLogger_CacheExpiryLessThanTenSeconds {
            get {
                return ResourceManager.GetString("MemoryLogger_CacheExpiryLessThanTenSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create memory logger as maximum log entries &apos;{0}&apos; was less than 1..
        /// </summary>
        internal static string MemoryLogger_MaximumLogsLessThanOne {
            get {
                return ResourceManager.GetString("MemoryLogger_MaximumLogsLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplication GUID provided for operation..
        /// </summary>
        internal static string Operation_DuplicateGuidProvided {
            get {
                return ResourceManager.GetString("Operation_DuplicateGuidProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot recover the operation&apos;s parent with GUID &apos;{0}&apos;..
        /// </summary>
        internal static string Operation_Parent_CannotRecoverParent {
            get {
                return ResourceManager.GetString("Operation_Parent_CannotRecoverParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; operation has already been stopped..
        /// </summary>
        internal static string Operation_Stop_OperationAlreadyStopped {
            get {
                return ResourceManager.GetString("Operation_Stop_OperationAlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{0}		Method: {2} ({3}){0}		Thread: {4} - {5}{0}		Guid: {6}{0}		Parent GUID: {7}{0}		Arguments: {8}.
        /// </summary>
        internal static string Operation_ToString {
            get {
                return ResourceManager.GetString("Operation_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred in the operation. {0}.
        /// </summary>
        internal static string Operation_Wrap_UnhandledExceptionOccurred {
            get {
                return ResourceManager.GetString("Operation_Wrap_UnhandledExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The performance counter category &apos;{0}&apos; does not exist, and must be created before it can be used..
        /// </summary>
        internal static string PerformanceCounterHelper_CategoryDoesNotExist {
            get {
                return ResourceManager.GetString("PerformanceCounterHelper_CategoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The performance counter category &apos;{0}&apos; does not contain a counter &apos;{1}, that must be created before it can be used..
        /// </summary>
        internal static string PerformanceCounterHelper_CounterDoesNotExist {
            get {
                return ResourceManager.GetString("PerformanceCounterHelper_CounterDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the performance counter category &apos;{0}&apos;..
        /// </summary>
        internal static string PerformanceCounterHelper_Create_Failed {
            get {
                return ResourceManager.GetString("PerformanceCounterHelper_Create_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete the performance counter category &apos;{0}&apos;..
        /// </summary>
        internal static string PerformanceCounterHelper_Delete_Failed {
            get {
                return ResourceManager.GetString("PerformanceCounterHelper_Delete_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current process identity does not have access to performance counters, disabling counters..
        /// </summary>
        internal static string PerformanceCounterHelper_ProcessDoesNotHaveAccess {
            get {
                return ResourceManager.GetString("PerformanceCounterHelper_ProcessDoesNotHaveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error occurred whilst initialising the counter category &apos;{0}&apos;..
        /// </summary>
        internal static string PerformanceCounterHelper_UnhandledExceptionOccurred {
            get {
                return ResourceManager.GetString("PerformanceCounterHelper_UnhandledExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The performance counter category &apos;{0}&apos; does not exist, and must be created before it can be used..
        /// </summary>
        internal static string PerformanceTimerHelper_Initialize_CategoryDoesNotExist {
            get {
                return ResourceManager.GetString("PerformanceTimerHelper_Initialize_CategoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error occurred whilst initialising the counter category &apos;{0}&apos;, disabling counters..
        /// </summary>
        internal static string PerformanceTimerHelper_Initialize_UnhandledExceptionOccurred {
            get {
                return ResourceManager.GetString("PerformanceTimerHelper_Initialize_UnhandledExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current process identity does not have access to performance counters, disabling counters..
        /// </summary>
        internal static string PerformanceTimerHelper_ProcessDoesNotHaveAccess {
            get {
                return ResourceManager.GetString("PerformanceTimerHelper_ProcessDoesNotHaveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register service &apos;{0}&apos;.
        /// </summary>
        internal static string SqlLogger_CouldNotRegisterService {
            get {
                return ResourceManager.GetString("SqlLogger_CouldNotRegisterService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot expire log entries in less than one second..
        /// </summary>
        internal static string Sqllogger_LogExpiryLessThanOneSecond {
            get {
                return ResourceManager.GetString("Sqllogger_LogExpiryLessThanOneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create SQL Logger as no connection string was supplied..
        /// </summary>
        internal static string SqlLogger_NoConnectionStringProvided {
            get {
                return ResourceManager.GetString("SqlLogger_NoConnectionStringProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified SQL timeout ({0}) was less than 1s..
        /// </summary>
        internal static string Sqllogger_TimeoutLessThanOneSecond {
            get {
                return ResourceManager.GetString("Sqllogger_TimeoutLessThanOneSecond", resourceCulture);
            }
        }
    }
}
