//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplications.Testing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplications.Testing.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; value of the {1} enum does could not be cleared with the value &apos;{2}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_Clear_CouldNotClearFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Clear_CouldNotClearFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not combine flags of type &apos;{0}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_Combine_CouldNotCombineFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Combine_CouldNotCombineFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} enum does not contain the name &apos;{1}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_DoesNotContainName {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_DoesNotContainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} enum does not contain the raw value &apos;{1}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_DoesNotContainRawValue {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_DoesNotContainRawValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} enum does not contain the value &apos;{1}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_DoesNotContainValue {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_DoesNotContainValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; value of the {1} enum does could not be intersected with the value &apos;{2}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_Intersect_CouldNotIntersectFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Intersect_CouldNotIntersectFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; value of the {1} enum does could not be inverted..
        /// </summary>
        internal static string ExtendedEnumGeneric_Invert_CouldNotInvertFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Invert_CouldNotInvertFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; value of the {1} enum could not be set with the value &apos;{2}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_Set_CouldNotSetFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_Set_CouldNotSetFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not split flags &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        internal static string ExtendedEnumGeneric_SplitFlags_CouldNotSplitFlags {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_SplitFlags_CouldNotSplitFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is a flag enum..
        /// </summary>
        internal static string ExtendedEnumGeneric_TypeIsFlagEnum {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_TypeIsFlagEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not an enum..
        /// </summary>
        internal static string ExtendedEnumGeneric_TypeIsNotAnEnum {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_TypeIsNotAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not a flag enum..
        /// </summary>
        internal static string ExtendedEnumGeneric_TypeIsNotFlagEnum {
            get {
                return ResourceManager.GetString("ExtendedEnumGeneric_TypeIsNotFlagEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast item at index {0} of Tuple from type {1} to type {2}..
        /// </summary>
        internal static string ExtendedTuple_CannotCastItemAtIndex {
            get {
                return ResourceManager.GetString("ExtendedTuple_CannotCastItemAtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuple &apos;{0}&apos; does not have a &apos;{1}&apos; property..
        /// </summary>
        internal static string ExtendedTuple_CouldNotFindProperty {
            get {
                return ResourceManager.GetString("ExtendedTuple_CouldNotFindProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuple &apos;{0}&apos; has more than 8 generic arguments, which is unsupported..
        /// </summary>
        internal static string ExtendedTuple_MoreThanEightGenericArguments {
            get {
                return ResourceManager.GetString("ExtendedTuple_MoreThanEightGenericArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not a valid tuple type..
        /// </summary>
        internal static string ExtendedTuple_TypeIsNotValidTuple {
            get {
                return ResourceManager.GetString("ExtendedTuple_TypeIsNotValidTuple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert the expression of type &apos;{0}&apos; to an expression of type &apos;{1}&apos;..
        /// </summary>
        internal static string Reflection_Convert_ConversionFailed {
            get {
                return ResourceManager.GetString("Reflection_Convert_ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda action from &apos;{0}&apos;, incorrect parameter count..
        /// </summary>
        internal static string Reflection_GetAction_IncorrectParameterCount {
            get {
                return ResourceManager.GetString("Reflection_GetAction_IncorrectParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda action from &apos;{0}&apos;, cannot assign type &apos;{1}&apos; to parameter of type &apos;{2}&apos;..
        /// </summary>
        internal static string Reflection_GetAction_ParameterNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetAction_ParameterNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, incorrect parameter count..
        /// </summary>
        internal static string Reflection_GetFunc_IncorrectParameterCount {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_IncorrectParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, as it is a method with no return type, use Action&lt;&gt;() instead..
        /// </summary>
        internal static string Reflection_GetFunc_MethodHasNoReturnType {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_MethodHasNoReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, as it is a static constructor..
        /// </summary>
        internal static string Reflection_GetFunc_MethodIsStaticConstructor {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_MethodIsStaticConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, no parameter/return types specified..
        /// </summary>
        internal static string Reflection_GetFunc_NoFuncTypesSpecified {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_NoFuncTypesSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, cannot assign type &apos;{1}&apos; to parameter of type &apos;{2}&apos;..
        /// </summary>
        internal static string Reflection_GetFunc_ParameterNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_ParameterNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function from &apos;{0}&apos;, cannot assign return type {1} to {2}..
        /// </summary>
        internal static string Reflection_GetFunc_ReturnTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetFunc_ReturnTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; getter on the type &apos;{1}&apos; as the name does not correspond to a field or property with a get accessor..
        /// </summary>
        internal static string Reflection_GetGetter_NoGetterForFieldOrProperty {
            get {
                return ResourceManager.GetString("Reflection_GetGetter_NoGetterForFieldOrProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} getter on the type &apos;{2}&apos; as the parameter type &apos;{3}&apos; is not assignable from the &apos;{2}&apos; declaring type..
        /// </summary>
        internal static string Reflection_GetGetter_ParameterTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetGetter_ParameterTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} getter on the type &apos;{2}&apos; as the {1} type &apos;{3}&apos; is not assignable to the &apos;{4}&apos; return type..
        /// </summary>
        internal static string Reflection_GetGetter_ReturnTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetGetter_ReturnTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} setter on the type &apos;{2}&apos; as the {1} type &apos;{3}&apos; is not assignable from the &apos;{4}&apos; value type..
        /// </summary>
        internal static string Reflection_GetSetter_MemberTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetSetter_MemberTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; setter on the type &apos;{1}&apos; as the name does not correspond to a field or property with a set accessor..
        /// </summary>
        internal static string Reflection_GetSetter_NoSetterForFieldOrProperty {
            get {
                return ResourceManager.GetString("Reflection_GetSetter_NoSetterForFieldOrProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} setter on the type &apos;{2}&apos; as the parameter type &apos;{3}&apos; is not assignable from the &apos;{2}&apos; declaring type..
        /// </summary>
        internal static string Reflection_GetSetter_ParameterTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetSetter_ParameterTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} setter on the type &apos;{2}&apos; as the {1} type &apos;{3}&apos; is not assignable to the &apos;{4}&apos; return type..
        /// </summary>
        internal static string Reflection_GetSetter_ReturnTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflection_GetSetter_ReturnTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; getter on the type &apos;{1}&apos; as the name does not correspond to a field or property with a get accessor..
        /// </summary>
        internal static string Reflector_GetGetter_DoesNotHaveGetter {
            get {
                return ResourceManager.GetString("Reflector_GetGetter_DoesNotHaveGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; does not exist on the type &apos;{1}&apos;..
        /// </summary>
        internal static string Reflector_GetGetter_MemberDoesNotExist {
            get {
                return ResourceManager.GetString("Reflector_GetGetter_MemberDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} getter on the type &apos;{2}&apos; as the parameter type &apos;{3}&apos; is not assignable from the &apos;{2}&apos; declaring type..
        /// </summary>
        internal static string Reflector_GetGetter_ParameterTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflector_GetGetter_ParameterTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a lambda function of the &apos;{0}&apos; {1} getter on the type &apos;{2}&apos; as the {1} type &apos;{3}&apos; is not assignable to the &apos;{4}&apos; return type..
        /// </summary>
        internal static string Reflector_GetGetter_ReturnTypeNotAssignable {
            get {
                return ResourceManager.GetString("Reflector_GetGetter_ReturnTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncating binary data of length &apos;{0}&apos; bytes when converting to SQL type &apos;{1}&apos; which only accepts &apos;{2}&apos; bytes..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_BinaryDataTruncated {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_BinaryDataTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured type &apos;{0}&apos; cannot accept an enumeration of &apos;{1}&apos;..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CannotAcceptEnumerationType {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CannotAcceptEnumerationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured type &apos;{0}&apos; cannot accept type &apos;{1}&apos;..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CannotAcceptType {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CannotAcceptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured type &apos;{0}&apos; cannot accept an enumeration of &apos;{1}&apos;.  Cannot cast &apos;{2}&apos; to &apos;{3}&apos; for the column with ordinal {4}..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CanNotCast {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CanNotCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured type &apos;{0}&apos; cannot accept an enumeration of &apos;{1}&apos;.  Cannot convert key type &apos;{2}&apos; to &apos;{3}&apos;..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CanNotConvertKeyType {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CanNotConvertKeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured type &apos;{0}&apos; cannot accept an enumeration of &apos;{1}&apos;.  The type only accepts {2} columns, but the tuple supplies &apos;{3}..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_ColumnNumberAndTupleSizeMismatch {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_ColumnNumberAndTupleSizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert binary data of length &apos;{0}&apos; bytes to SQL type &apos;{1}&apos; which only accepts &apos;{2}&apos; bytes..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CouldNotConvertBinaryData {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CouldNotConvertBinaryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert DateTime &apos;{0}&apos; to SQL type &apos;{1}&apos; which only accepts DateTimes in the &apos;{2}&apos; range..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CouldNotConvertDateTimeToSqlType {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CouldNotConvertDateTimeToSqlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert string of length &apos;{0}&apos; characters to SQL type &apos;{1}&apos; which only accepts &apos;{2}&apos; characters..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CouldNotConvertString {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CouldNotConvertString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not serialize object of type &apos;{0}&apos; into SQL type &apos;{1}&apos; as it requires &apos;{2}&apos; bytes and the SQL type only accepts &apos;{3}&apos; bytes..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CouldNotSerializeObject {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CouldNotSerializeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncating DateTime &apos;{0}&apos; when converting to SQL type &apos;{1}&apos; which only accepts DateTimes in the &apos;{2}&apos; range..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_DateTimeTruncated {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_DateTimeTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error whilst trying to create type convertor for &apos;{0}&apos; type on SQL Type &apos;{1}&apos;. {2}.
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_FatalErrorOccurred {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_FatalErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured type &apos;{0}&apos; was not created as a SqlTableType..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_NotCreatedAsSqlTableType {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_NotCreatedAsSqlTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No type specified for converting to SQL Type &apos;{0}&apos;..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_NoTypeSpecified {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_NoTypeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not pass string into SQL type &apos;{0}&apos; as it contains Unicode characters and the SQL type only accepts ASCII characters..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_StringContainsUnicodeCharacters {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_StringContainsUnicodeCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncating string of length &apos;{0}&apos; characters when converting to SQL type &apos;{1}&apos; which only accepts &apos;{2}&apos; characters..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_StringTruncated {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_StringTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDT type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_UdtTypeNotSupported {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_UdtTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losing Unicode characters when converting string into SQL type &apos;{0}&apos; as the SQL type only accepts ASCII characters..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_UnicodeCharactersLost {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_UnicodeCharactersLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported SqlDbType &apos;{0}&apos;..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_UnsupportedSqlDbType {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_UnsupportedSqlDbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown SQL system type found &apos;{0}&apos;, trying NVarChar..
        /// </summary>
        internal static string SqlType_UnknownSqlSystemType {
            get {
                return ResourceManager.GetString("SqlType_UnknownSqlSystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length: {0}; Precision: {1}; Scale: {2}..
        /// </summary>
        internal static string SqlTypeSize_ToString {
            get {
                return ResourceManager.GetString("SqlTypeSize_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast an unknown TriState to a Boolean.
        /// </summary>
        internal static string TriState_ExplicitBoolConversion_CannotCastUnknownState {
            get {
                return ResourceManager.GetString("TriState_ExplicitBoolConversion_CannotCastUnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast byte &apos;{0}&apos; to TriState, value must be less than 3..
        /// </summary>
        internal static string TriState_ExplicitByteConversion_ValueGreaterThanThree {
            get {
                return ResourceManager.GetString("TriState_ExplicitByteConversion_ValueGreaterThanThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} format string is not supported..
        /// </summary>
        internal static string TriState_ToString_FormatException {
            get {
                return ResourceManager.GetString("TriState_ToString_FormatException", resourceCulture);
            }
        }
    }
}
