//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplications.Utilities.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplications.Utilities.Service.ServiceResources", typeof(ServiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue the service..
        /// </summary>
        internal static string Cmd_Continue_Description {
            get {
                return ResourceManager.GetString("Cmd_Continue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue,Cont,C.
        /// </summary>
        internal static string Cmd_Continue_Names {
            get {
                return ResourceManager.GetString("Cmd_Continue_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes the custom command number, e.g. command 54..
        /// </summary>
        internal static string Cmd_CustomCommand_Description {
            get {
                return ResourceManager.GetString("Cmd_CustomCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command,Execute,Exec,..
        /// </summary>
        internal static string Cmd_CustomCommand_Names {
            get {
                return ResourceManager.GetString("Cmd_CustomCommand_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description is available for the command in the current language..
        /// </summary>
        internal static string Cmd_Description {
            get {
                return ResourceManager.GetString("Cmd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs this help..
        /// </summary>
        internal static string Cmd_Help_Description {
            get {
                return ResourceManager.GetString("Cmd_Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help,?.
        /// </summary>
        internal static string Cmd_Help_Names {
            get {
                return ResourceManager.GetString("Cmd_Help_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the logformat..
        /// </summary>
        internal static string Cmd_LogFormat_Description {
            get {
                return ResourceManager.GetString("Cmd_LogFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogFormat,lf.
        /// </summary>
        internal static string Cmd_LogFormat_Names {
            get {
                return ResourceManager.GetString("Cmd_LogFormat_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the logging levels..
        /// </summary>
        internal static string Cmd_LogLevels_Description {
            get {
                return ResourceManager.GetString("Cmd_LogLevels_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogLevels,ll.
        /// </summary>
        internal static string Cmd_LogLevels_Names {
            get {
                return ResourceManager.GetString("Cmd_LogLevels_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauses the service..
        /// </summary>
        internal static string Cmd_Pause_Description {
            get {
                return ResourceManager.GetString("Cmd_Pause_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause,P.
        /// </summary>
        internal static string Cmd_Pause_Names {
            get {
                return ResourceManager.GetString("Cmd_Pause_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends the power status to the service, e.g. power Suspend..
        /// </summary>
        internal static string Cmd_PowerEvent_Description {
            get {
                return ResourceManager.GetString("Cmd_PowerEvent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string Cmd_PowerEvent_Names {
            get {
                return ResourceManager.GetString("Cmd_PowerEvent_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a session changed notice to the service, e.g session SessionLogon 0.
        /// </summary>
        internal static string Cmd_SessionChange_Description {
            get {
                return ResourceManager.GetString("Cmd_SessionChange_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string Cmd_SessionChange_Names {
            get {
                return ResourceManager.GetString("Cmd_SessionChange_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuts down the service and quits..
        /// </summary>
        internal static string Cmd_Shutdown_Description {
            get {
                return ResourceManager.GetString("Cmd_Shutdown_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown,Quit,Exit,X.
        /// </summary>
        internal static string Cmd_Shutdown_Names {
            get {
                return ResourceManager.GetString("Cmd_Shutdown_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the service, passing in the specified arguments, e.g. start arg1 arg2 arg3..
        /// </summary>
        internal static string Cmd_Start_Description {
            get {
                return ResourceManager.GetString("Cmd_Start_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start,Go,G.
        /// </summary>
        internal static string Cmd_Start_Names {
            get {
                return ResourceManager.GetString("Cmd_Start_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops the service..
        /// </summary>
        internal static string Cmd_Stop_Description {
            get {
                return ResourceManager.GetString("Cmd_Stop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop,S.
        /// </summary>
        internal static string Cmd_Stop_Names {
            get {
                return ResourceManager.GetString("Cmd_Stop_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error executing the &apos;{0}&apos; command..
        /// </summary>
        internal static string Err_Comman_Exception {
            get {
                return ResourceManager.GetString("Err_Comman_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; command was not found on the &apos;{1}&apos; instance..
        /// </summary>
        internal static string Err_Command_Not_On_Instance {
            get {
                return ResourceManager.GetString("Err_Command_Not_On_Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No console logger has been set!.
        /// </summary>
        internal static string Err_No_Console_Logger {
            get {
                return ResourceManager.GetString("Err_No_Console_Logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command method &apos;{0}&apos;. A service runner command with ConsumeLine set must declare exactly one string parameter..
        /// </summary>
        internal static string Err_ServiceCommand_Invalid_Command_Method {
            get {
                return ResourceManager.GetString("Err_ServiceCommand_Invalid_Command_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert string to &apos;{0}&apos; for parameter &apos;{1}&apos; on method &apos;{2}&apos;..
        /// </summary>
        internal static string Err_ServiceCommand_Parameter_Conversion_Unsupported {
            get {
                return ResourceManager.GetString("Err_ServiceCommand_Parameter_Conversion_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; service is not paused!.
        /// </summary>
        internal static string Err_ServiceRunner_Continue_ServiceNotPaused {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_Continue_ServiceNotPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; service is not running, so cannot be paused!.
        /// </summary>
        internal static string Err_ServiceRunner_Pause_ServiceNotRunning {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_Pause_ServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command number &apos;{0}&apos; must be an integer..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_CommandParameterInvalid {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_CommandParameterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command requires one parameters, a command number..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_CommandParameterMissing {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_CommandParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run the &apos;{0}&apos; service in interactive mode as no console found!.
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_ConsoleNotFound {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_ConsoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue does not accept parameters..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_ContinueParameters {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_ContinueParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LoggingLevels &apos;{0}&apos; must be one of: {1}..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_LoggingLevelsInvalid {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_LoggingLevelsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loglevels allows one parameters, a LoggingLevels..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_LoggingLevelsTooManyParameters {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_LoggingLevelsTooManyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause does not accept parameters..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_PauseParameters {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_PauseParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power requires one parameters, a PowerBroadcastStatus..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_PowerParameterMissing {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_PowerParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PowerBroadcastStatus &apos;{0}&apos; must be one of: {1}..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_PowerParamterInvalid {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_PowerParamterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SessionChangeReason &apos;{0}&apos; must be one of: {1}..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_SessionChangeInvalid {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_SessionChangeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session id &apos;{0}&apos; must be an integer..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_SessionIdInvalid {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_SessionIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session requires two parameters, a SessionChangeReason and a Session id..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_SessionParamtersMissing {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_SessionParamtersMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown does not accept parameters..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_ShutdownParameters {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_ShutdownParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop does not accept parameters..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_StopParameters {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_StopParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command &apos;{0}&apos;..
        /// </summary>
        internal static string Err_ServiceRunner_RunInteractive_UnknownCommand {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_RunInteractive_UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; service is already running!.
        /// </summary>
        internal static string Err_ServiceRunner_ServiceAlreadyRunning {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_ServiceAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; service is not interactive!.
        /// </summary>
        internal static string Err_ServiceRunner_ServiceNotInteractive {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_ServiceNotInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; service is not running, so cannot be stopped!.
        /// </summary>
        internal static string Err_ServiceRunner_Stop_ServiceNotRunning {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_Stop_ServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continued service &apos;{0}&apos; in {1}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_Continue_Continued {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Continue_Continued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing service &apos;{0}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_Continue_Continuing {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Continue_Continuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; does not support continue..
        /// </summary>
        internal static string Inf_ServiceRunner_Continue_NotSupported {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Continue_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running &apos;{0}&apos; custom command on service &apos;{1}&apos; took {2}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_CustomCommand_Complete {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_CustomCommand_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running &apos;{0}&apos; custom command on service &apos;{1}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_CustomCommand_Running {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_CustomCommand_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; already disposed..
        /// </summary>
        internal static string Inf_ServiceRunner_Dispose_AlreadyDisposed {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Dispose_AlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposed service &apos;{0}&apos; in {1}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_Dispose_Disposed {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Dispose_Disposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing service &apos;{0}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_Dispose_Disposing {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Dispose_Disposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; does not support pausing..
        /// </summary>
        internal static string Inf_ServiceRunner_Pause_NotSupported {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Pause_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused service &apos;{0}&apos; in {1}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_Pause_Paused {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Pause_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing service &apos;{0}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_Pause_Pausing {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Pause_Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; does not support power events..
        /// </summary>
        internal static string Inf_ServiceRunner_PowerEvent_NotSupported {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_PowerEvent_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the &apos;{0}&apos; power event to service &apos;{1}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_PowerEvent_Sending {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_PowerEvent_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the &apos;{0}&apos; power event to service &apos;{1}&apos; took {2}ms, and returned &apos;{3}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_PowerEvent_Sent {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_PowerEvent_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; service is running in non-interactive mode.
        /// </summary>
        internal static string Inf_ServiceRunner_RunAsService_ServiceNotInteractive {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_RunAsService_ServiceNotInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; does not support session change events..
        /// </summary>
        internal static string Inf_ServiceRunner_SessionChange_NotSupported {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_SessionChange_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the &apos;{0}&apos; session change event for session &apos;{1}&apos; to service &apos;{2}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_SessionChange_Sending {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_SessionChange_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the &apos;{0}&apos; session change event for session &apos;{1}&apos; to service &apos;{2}&apos; took {3}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_SessionChange_Sent {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_SessionChange_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; does not support shutdown..
        /// </summary>
        internal static string Inf_ServiceRunner_Shutdown_NotSupported {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Shutdown_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut down service &apos;{0}&apos; in {1}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_Shutdown_ShutDown {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Shutdown_ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down service &apos;{0}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_Shutdown_ShuttingDown {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Shutdown_ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started service &apos;{0}&apos; in {1}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_Start_Started {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Start_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service &apos;{0}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_Start_Starting {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Start_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; does not support stopping..
        /// </summary>
        internal static string Inf_ServiceRunner_Stop_NotSupported {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Stop_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped service &apos;{0}&apos; in {1}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_Stop_Stopped {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Stop_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping service &apos;{0}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_Stop_Stopping {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Stop_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; command alias for &apos;{1}&apos; is already used by the &apos;{2}&apos; command..
        /// </summary>
        internal static string Wrn_Command_Alias_Already_Used_By_Other_Command {
            get {
                return ResourceManager.GetString("Wrn_Command_Alias_Already_Used_By_Other_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; command on the &apos;{1}&apos; type has already been registered by the &apos;{2}&apos; type..
        /// </summary>
        internal static string Wrn_Command_Already_Registered {
            get {
                return ResourceManager.GetString("Wrn_Command_Already_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; method cannot implement a service runner command as it is generic..
        /// </summary>
        internal static string Wrn_Command_Invalid_Generic {
            get {
                return ResourceManager.GetString("Wrn_Command_Invalid_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description was specified for the &apos;{0}&apos; command..
        /// </summary>
        internal static string Wrn_No_Description_For_Command {
            get {
                return ResourceManager.GetString("Wrn_No_Description_For_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No names were found for the &apos;{0}&apos; command..
        /// </summary>
        internal static string Wrn_No_Names_For_Command {
            get {
                return ResourceManager.GetString("Wrn_No_Names_For_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a service runner command for the &apos;{0}&apos; method.
        /// </summary>
        internal static string Wrn_ServiceCommand_Creation_Failed {
            get {
                return ResourceManager.GetString("Wrn_ServiceCommand_Creation_Failed", resourceCulture);
            }
        }
    }
}
