//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplications.Utilities.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplications.Utilities.Service.ServiceResources", typeof(ServiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue the service..
        /// </summary>
        internal static string Cmd_Continue_Description {
            get {
                return ResourceManager.GetString("Cmd_Continue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue,Cont,C.
        /// </summary>
        internal static string Cmd_Continue_Names {
            get {
                return ResourceManager.GetString("Cmd_Continue_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application-defined command flag that indicates which custom command to execute. The value must be between 128 and 256, inclusive..
        /// </summary>
        internal static string Cmd_CustomCommand_Command_Description {
            get {
                return ResourceManager.GetString("Cmd_CustomCommand_Command_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes the custom command number, e.g. command 135..
        /// </summary>
        internal static string Cmd_CustomCommand_Description {
            get {
                return ResourceManager.GetString("Cmd_CustomCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command,Execute,Exec,..
        /// </summary>
        internal static string Cmd_CustomCommand_Names {
            get {
                return ResourceManager.GetString("Cmd_CustomCommand_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description is available for the command in the current language..
        /// </summary>
        internal static string Cmd_Description {
            get {
                return ResourceManager.GetString("Cmd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from the service without shutting it down.  If running in interactive console mode, consider using the Shutdown if you wish the service to cleanly exit..
        /// </summary>
        internal static string Cmd_Disconnect_Description {
            get {
                return ResourceManager.GetString("Cmd_Disconnect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit,Exit,X,Disconnect.
        /// </summary>
        internal static string Cmd_Disconnect_Names {
            get {
                return ResourceManager.GetString("Cmd_Disconnect_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the command to get help for. If omitted, all commands will be listed..
        /// </summary>
        internal static string Cmd_Help_Command_Description {
            get {
                return ResourceManager.GetString("Cmd_Help_Command_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs this help..
        /// </summary>
        internal static string Cmd_Help_Description {
            get {
                return ResourceManager.GetString("Cmd_Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help,?.
        /// </summary>
        internal static string Cmd_Help_Names {
            get {
                return ResourceManager.GetString("Cmd_Help_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the parameter to get help for. If omitted, all parameters of the command will be listed..
        /// </summary>
        internal static string Cmd_Help_Parameter_Description {
            get {
                return ResourceManager.GetString("Cmd_Help_Parameter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description is available for the parameter in the current language..
        /// </summary>
        internal static string Cmd_Param_Description {
            get {
                return ResourceManager.GetString("Cmd_Param_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauses the service..
        /// </summary>
        internal static string Cmd_Pause_Description {
            get {
                return ResourceManager.GetString("Cmd_Pause_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause,P.
        /// </summary>
        internal static string Cmd_Pause_Names {
            get {
                return ResourceManager.GetString("Cmd_Pause_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the performance counter to get the details of. If omitted, all performance counters will be listed..
        /// </summary>
        internal static string Cmd_Performance_Category_Description {
            get {
                return ResourceManager.GetString("Cmd_Performance_Category_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the performance counters for this service..
        /// </summary>
        internal static string Cmd_Performance_Description {
            get {
                return ResourceManager.GetString("Cmd_Performance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perf,Performance.
        /// </summary>
        internal static string Cmd_Performance_Names {
            get {
                return ResourceManager.GetString("Cmd_Performance_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends the power status to the service, e.g. power Suspend..
        /// </summary>
        internal static string Cmd_PowerEvent_Description {
            get {
                return ResourceManager.GetString("Cmd_PowerEvent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string Cmd_PowerEvent_Names {
            get {
                return ResourceManager.GetString("Cmd_PowerEvent_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The power status to send to the service.  This is only available in interactive mode..
        /// </summary>
        internal static string Cmd_PowerEvent_PowerStatus_Description {
            get {
                return ResourceManager.GetString("Cmd_PowerEvent_PowerStatus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason for the change notice..
        /// </summary>
        internal static string Cmd_SessionChange_ChangeReason_Description {
            get {
                return ResourceManager.GetString("Cmd_SessionChange_ChangeReason_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a session changed notice to the service, e.g session SessionLogon 0.
        /// </summary>
        internal static string Cmd_SessionChange_Description {
            get {
                return ResourceManager.GetString("Cmd_SessionChange_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string Cmd_SessionChange_Names {
            get {
                return ResourceManager.GetString("Cmd_SessionChange_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the session..
        /// </summary>
        internal static string Cmd_SessionChange_SessionID_Description {
            get {
                return ResourceManager.GetString("Cmd_SessionChange_SessionID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuts down the service and quits.  This is only available in interactive mode..
        /// </summary>
        internal static string Cmd_Shutdown_Description {
            get {
                return ResourceManager.GetString("Cmd_Shutdown_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string Cmd_Shutdown_Names {
            get {
                return ResourceManager.GetString("Cmd_Shutdown_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service start arguments..
        /// </summary>
        internal static string Cmd_Start_Args_Description {
            get {
                return ResourceManager.GetString("Cmd_Start_Args_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the service, passing in the specified arguments, e.g. start arg1 arg2 arg3..
        /// </summary>
        internal static string Cmd_Start_Description {
            get {
                return ResourceManager.GetString("Cmd_Start_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start,Go,G.
        /// </summary>
        internal static string Cmd_Start_Names {
            get {
                return ResourceManager.GetString("Cmd_Start_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops the service..
        /// </summary>
        internal static string Cmd_Stop_Description {
            get {
                return ResourceManager.GetString("Cmd_Stop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop,S.
        /// </summary>
        internal static string Cmd_Stop_Names {
            get {
                return ResourceManager.GetString("Cmd_Stop_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error executing the &apos;{0}&apos; command..
        /// </summary>
        internal static string Err_Command_Exception {
            get {
                return ResourceManager.GetString("Err_Command_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; command failed..
        /// </summary>
        internal static string Err_Command_Failed {
            get {
                return ResourceManager.GetString("Err_Command_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occurred on the current named pipe connection, closing..
        /// </summary>
        internal static string Err_NamedPipeConnection_Failed {
            get {
                return ResourceManager.GetString("Err_NamedPipeConnection_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the current security identity for securing a named pipe, so aborting..
        /// </summary>
        internal static string Err_NamedPipeServer_CannotGetCurrentOwner {
            get {
                return ResourceManager.GetString("Err_NamedPipeServer_CannotGetCurrentOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occurred trying to secure the named pipe server..
        /// </summary>
        internal static string Err_NamedPipeServer_Fatal_Error_Securing {
            get {
                return ResourceManager.GetString("Err_NamedPipeServer_Fatal_Error_Securing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command method &apos;{0}&apos;. A service runner command with ConsumeLine set must declare exactly one string parameter..
        /// </summary>
        internal static string Err_ServiceCommand_Invalid_Command_Method {
            get {
                return ResourceManager.GetString("Err_ServiceCommand_Invalid_Command_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert string to &apos;{0}&apos; for parameter &apos;{1}&apos; on method &apos;{2}&apos;..
        /// </summary>
        internal static string Err_ServiceCommand_Parameter_Conversion_Unsupported {
            get {
                return ResourceManager.GetString("Err_ServiceCommand_Parameter_Conversion_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; service is not paused!.
        /// </summary>
        internal static string Err_ServiceRunner_Continue_ServiceNotPaused {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_Continue_ServiceNotPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; service is not running, so cannot be paused!.
        /// </summary>
        internal static string Err_ServiceRunner_Pause_ServiceNotRunning {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_Pause_ServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; service is already running!.
        /// </summary>
        internal static string Err_ServiceRunner_ServiceAlreadyRunning {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_ServiceAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; service is not interactive!.
        /// </summary>
        internal static string Err_ServiceRunner_ServiceNotInteractive {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_ServiceNotInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; service is not running, so cannot be stopped!.
        /// </summary>
        internal static string Err_ServiceRunner_Stop_ServiceNotRunning {
            get {
                return ResourceManager.GetString("Err_ServiceRunner_Stop_ServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; command is not supported by the service..
        /// </summary>
        internal static string Err_Unknown_Command {
            get {
                return ResourceManager.GetString("Err_Unknown_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continued service &apos;{0}&apos; in {1}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_Continue_Continued {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Continue_Continued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing service &apos;{0}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_Continue_Continuing {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Continue_Continuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running &apos;{0}&apos; custom command on service &apos;{1}&apos; took {2}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_CustomCommand_Complete {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_CustomCommand_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running &apos;{0}&apos; custom command on service &apos;{1}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_CustomCommand_Running {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_CustomCommand_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; already disposed..
        /// </summary>
        internal static string Inf_ServiceRunner_Dispose_AlreadyDisposed {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Dispose_AlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposed service &apos;{0}&apos; in {1}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_Dispose_Disposed {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Dispose_Disposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing service &apos;{0}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_Dispose_Disposing {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Dispose_Disposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused service &apos;{0}&apos; in {1}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_Pause_Paused {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Pause_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing service &apos;{0}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_Pause_Pausing {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Pause_Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the &apos;{0}&apos; power event to service &apos;{1}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_PowerEvent_Sending {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_PowerEvent_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the &apos;{0}&apos; power event to service &apos;{1}&apos; took {2}ms, and returned &apos;{3}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_PowerEvent_Sent {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_PowerEvent_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the &apos;{0}&apos; session change event for session &apos;{1}&apos; to service &apos;{2}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_SessionChange_Sending {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_SessionChange_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the &apos;{0}&apos; session change event for session &apos;{1}&apos; to service &apos;{2}&apos; took {3}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_SessionChange_Sent {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_SessionChange_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut down service &apos;{0}&apos; in {1}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_Shutdown_ShutDown {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Shutdown_ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down service &apos;{0}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_Shutdown_ShuttingDown {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Shutdown_ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started service &apos;{0}&apos; in {1}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_Start_Started {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Start_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service &apos;{0}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_Start_Starting {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Start_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped service &apos;{0}&apos; in {1}ms..
        /// </summary>
        internal static string Inf_ServiceRunner_Stop_Stopped {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Stop_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping service &apos;{0}&apos;..
        /// </summary>
        internal static string Inf_ServiceRunner_Stop_Stopping {
            get {
                return ResourceManager.GetString("Inf_ServiceRunner_Stop_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; command alias for &apos;{1}&apos; is already used by the &apos;{2}&apos; command..
        /// </summary>
        internal static string Wrn_Command_Alias_Already_Used_By_Other_Command {
            get {
                return ResourceManager.GetString("Wrn_Command_Alias_Already_Used_By_Other_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; method cannot implement a service runner command as it is generic..
        /// </summary>
        internal static string Wrn_Command_Invalid_Generic {
            get {
                return ResourceManager.GetString("Wrn_Command_Invalid_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description was specified for the &apos;{0}&apos; command..
        /// </summary>
        internal static string Wrn_No_Description_For_Command {
            get {
                return ResourceManager.GetString("Wrn_No_Description_For_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description was specified for the &apos;{0}&apos; parameter in the &apos;{1}&apos; command..
        /// </summary>
        internal static string Wrn_No_Description_For_Parameter {
            get {
                return ResourceManager.GetString("Wrn_No_Description_For_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No names were found for the &apos;{0}&apos; command..
        /// </summary>
        internal static string Wrn_No_Names_For_Command {
            get {
                return ResourceManager.GetString("Wrn_No_Names_For_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a service runner command for the &apos;{0}&apos; method.
        /// </summary>
        internal static string Wrn_ServiceCommand_Creation_Failed {
            get {
                return ResourceManager.GetString("Wrn_ServiceCommand_Creation_Failed", resourceCulture);
            }
        }
    }
}
