//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplications.Utilities.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplications.Utilities.Database.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database with id &apos;{0}&apos; could not be found in the configuration..
        /// </summary>
        internal static string DatabaseConfiguration_GetSqlProgram_DatabaseIdNotFound {
            get {
                return ResourceManager.GetString("DatabaseConfiguration_GetSqlProgram_DatabaseIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a default load balanced connection for the database with id &apos;{0}&apos;..
        /// </summary>
        internal static string DatabaseElement_GetSqlProgram_DefaultLoadBalanceConnectionNotFound {
            get {
                return ResourceManager.GetString("DatabaseElement_GetSqlProgram_DefaultLoadBalanceConnectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a valid mapping for &apos;{0}&apos; parameter on &apos;{1}&apos; program..
        /// </summary>
        internal static string DatabaseElement_GetSqlProgram_Invalid_Mapping {
            get {
                return ResourceManager.GetString("DatabaseElement_GetSqlProgram_Invalid_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a load balanced connection with id &apos;{0}&apos; for the database with id &apos;{1}&apos; for use with the &apos;{2}&apos; SqlProgram..
        /// </summary>
        internal static string DatabaseElement_GetSqlProgram_LoadBalanceConnectionNotFound {
            get {
                return ResourceManager.GetString("DatabaseElement_GetSqlProgram_LoadBalanceConnectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a valid mapping for &apos;{0}&apos; parameter on &apos;{1}&apos; program..
        /// </summary>
        internal static string DatabaseElement_GetSqlProgram_MappingNotSpecified {
            get {
                return ResourceManager.GetString("DatabaseElement_GetSqlProgram_MappingNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a default load balanced connection for the database with id &apos;{0}&apos;..
        /// </summary>
        internal static string DatabaseElement_GetSqlProgram_Unknown_Database {
            get {
                return ResourceManager.GetString("DatabaseElement_GetSqlProgram_Unknown_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a load balanced connection with id &apos;{0}&apos; for the database with id &apos;{1}&apos; for use with the &apos;{2}&apos; SqlProgram..
        /// </summary>
        internal static string DatabaseElement_GetSqlProgram_Unknown_Database_Program {
            get {
                return ResourceManager.GetString("DatabaseElement_GetSqlProgram_Unknown_Database_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find column &apos;{0}&apos;s type &apos;{1}&apos; when loading table/view definition for &apos;{2}&apos;..
        /// </summary>
        internal static string DatabaseSchema_Load_ColumnTypeNotFound {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_ColumnTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find SQL object type &apos;{0}&apos; when loading tables/views..
        /// </summary>
        internal static string DatabaseSchema_Load_CouldNotFindObjectType {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_CouldNotFindObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find schema &apos;{0}&apos; when loading types..
        /// </summary>
        internal static string DatabaseSchema_Load_CouldNotFindSchema {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_CouldNotFindSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find schema &apos;{0}&apos; when loading table/view definitions..
        /// </summary>
        internal static string DatabaseSchema_Load_CouldNotFindSchemaLoadingTablesAndViews {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_CouldNotFindSchemaLoadingTablesAndViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find schema &apos;{0}&apos; when loading program definitions..
        /// </summary>
        internal static string DatabaseSchema_Load_CouldNotFindSchemaWhenLoadingPrograms {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_CouldNotFindSchemaWhenLoadingPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find SQL object type &apos;{0}&apos; when loading program definitions..
        /// </summary>
        internal static string DatabaseSchema_Load_CouldNotFindTypeWhenLoadingPrograms {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_CouldNotFindTypeWhenLoadingPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse version information of SQL server..
        /// </summary>
        internal static string DatabaseSchema_Load_CouldNotParseVersionInformation {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_CouldNotParseVersionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve schemas from database..
        /// </summary>
        internal static string DatabaseSchema_Load_CouldNotRetrieveSchemas {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_CouldNotRetrieveSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve types from database..
        /// </summary>
        internal static string DatabaseSchema_Load_CouldNotRetrieveTypes {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_CouldNotRetrieveTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred whilst trying to retrieve information about a SQL programmability object..
        /// </summary>
        internal static string DatabaseSchema_Load_ErrorOccurred {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent object type when loading &apos;{0}&apos; program definition..
        /// </summary>
        internal static string DatabaseSchema_Load_InconsistentType {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_InconsistentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent object type when loading &apos;{0}&apos; table/view definition..
        /// </summary>
        internal static string DatabaseSchema_Load_InconsistentTypeLoadingTablesAndViews {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_InconsistentTypeLoadingTablesAndViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find parameter &apos;{0}&apos;s type &apos;{1}&apos; when loading program definition for &apos;{2}&apos;..
        /// </summary>
        internal static string DatabaseSchema_Load_ParameterTypeNotFound {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_ParameterTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ran out of results retrieving programs from database..
        /// </summary>
        internal static string DatabaseSchema_Load_RanOutOfResultsRetrievingPrograms {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_RanOutOfResultsRetrievingPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ran out of results retrieving types from database..
        /// </summary>
        internal static string DatabaseSchema_Load_RanOutOfResultsRetrievingTypes {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_RanOutOfResultsRetrievingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ran out of results retrieving tables and views from database..
        /// </summary>
        internal static string DatabaseSchema_Load_RanOutOfTablesAndViews {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_RanOutOfTablesAndViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find table type &apos;{0}&apos;s which is associated with table definition for &apos;{1}&apos;..
        /// </summary>
        internal static string DatabaseSchema_Load_TableTypeNotFound {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_TableTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not a table type, but it&apos;s supposedly associated with the table definition for &apos;{1}&apos;..
        /// </summary>
        internal static string DatabaseSchema_Load_TypeNotTableType {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_TypeNotTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL database version &apos;{0}&apos; is not currently supported..
        /// </summary>
        internal static string DatabaseSchema_Load_VersionNotSupported {
            get {
                return ResourceManager.GetString("DatabaseSchema_Load_VersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;fullName&apos; can not be null.
        /// </summary>
        internal static string DatabaseSchema_TypeGetType_FullNameCanNotBeNull {
            get {
                return ResourceManager.GetString("DatabaseSchema_TypeGetType_FullNameCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database with id &apos;{0}&apos; could not be found in the configuration..
        /// </summary>
        internal static string DatabasesConfiguration_GetSqlProgram_Unknown_Database {
            get {
                return ResourceManager.GetString("DatabasesConfiguration_GetSqlProgram_Unknown_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify at least one connection string, with a weight greater than zero..
        /// </summary>
        internal static string LoadBalancedConnection_AllStringsZeroWeighted {
            get {
                return ResourceManager.GetString("LoadBalancedConnection_AllStringsZeroWeighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to select a valid connection string from the load balanced collection..
        /// </summary>
        internal static string LoadBalancedConnection_CreateConnection_NoValidConnectionString {
            get {
                return ResourceManager.GetString("LoadBalancedConnection_CreateConnection_NoValidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify at least one connection string..
        /// </summary>
        internal static string LoadBalancedConnection_NoConnectionStrings {
            get {
                return ResourceManager.GetString("LoadBalancedConnection_NoConnectionStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection strings must point to databases with identical schemas..
        /// </summary>
        internal static string LoadBalancedConnection_ReloadSchemas_SchemasNotIdentical {
            get {
                return ResourceManager.GetString("LoadBalancedConnection_ReloadSchemas_SchemasNotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection strings must point to databases with identical schemas..
        /// </summary>
        internal static string LoadBalancedConnection_SchemasNotIdentical {
            get {
                return ResourceManager.GetString("LoadBalancedConnection_SchemasNotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load balanced connection string with &apos;{0}&apos; connections..
        /// </summary>
        internal static string LoadBalancedConnection_ToString {
            get {
                return ResourceManager.GetString("LoadBalancedConnection_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string weight must not be less than zero..
        /// </summary>
        internal static string LoadBalancedConnection_WeightLessThanZero {
            get {
                return ResourceManager.GetString("LoadBalancedConnection_WeightLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported SqlDbType &apos;{0}&apos;..
        /// </summary>
        internal static string SqlMetaType_GetMetaTypeFromSqlDbType_UnsupportedType {
            get {
                return ResourceManager.GetString("SqlMetaType_GetMetaTypeFromSqlDbType_UnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program definitions for &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string SqlProgram_Validate_DefinitionsNotFound {
            get {
                return ResourceManager.GetString("SqlProgram_Validate_DefinitionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent program definitions for &apos;{0}&apos; found in different connections..
        /// </summary>
        internal static string SqlProgram_Validate_InconsistentProgramDefinitions {
            get {
                return ResourceManager.GetString("SqlProgram_Validate_InconsistentProgramDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL Program &apos;{0}&apos; does not have a &apos;{1}&apos; parameter..
        /// </summary>
        internal static string SqlProgramCommand_GetParameter_ProgramDoesNotHaveParameter {
            get {
                return ResourceManager.GetString("SqlProgramCommand_GetParameter_ProgramDoesNotHaveParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL Program &apos;{0}&apos; does not have a &apos;{1}&apos; parameter..
        /// </summary>
        internal static string SqlProgramCommand_SetParameter_ProgramDoesNotHaveParameter {
            get {
                return ResourceManager.GetString("SqlProgramCommand_SetParameter_ProgramDoesNotHaveParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many parameters supplied for the &apos;{0}&apos; program, which only accepts &apos;{1} parameter(s) but was supplied with &apos;{2}&apos;..
        /// </summary>
        internal static string SqlProgramCommand_SetParameters_Too_Many_Parameters {
            get {
                return ResourceManager.GetString("SqlProgramCommand_SetParameters_Too_Many_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL Program &apos;{0}&apos; does not have a &apos;{1}&apos; parameter..
        /// </summary>
        internal static string SqlProgramCommand_SetParameters_Unknown_Parameter {
            get {
                return ResourceManager.GetString("SqlProgramCommand_SetParameters_Unknown_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong number of parameters supplied for the &apos;{0}&apos; program, which expected &apos;{1}&apos; parameter(s) but was supplied with &apos;{2}..
        /// </summary>
        internal static string SqlProgramCommand_SetParameters_Wrong_Number_Of_Parameters {
            get {
                return ResourceManager.GetString("SqlProgramCommand_SetParameters_Wrong_Number_Of_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SqlProgramCommand for the &apos;{0}&apos; SqlProgram.
        /// </summary>
        internal static string SqlProgramCommand_ToString {
            get {
                return ResourceManager.GetString("SqlProgramCommand_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program has &apos;{0}&apos; parameter types, so can not have &apos;{1}&apos; parameter names!.
        /// </summary>
        internal static string SqlProgramDefinition_ToKVP_TypeAndNameCountNotEqual {
            get {
                return ResourceManager.GetString("SqlProgramDefinition_ToKVP_TypeAndNameCountNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Program Definition.
        /// </summary>
        internal static string SqlProgramDefinition_ToString {
            get {
                return ResourceManager.GetString("SqlProgramDefinition_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a parameter name when not validating parameter order of parameters on the program called &apos;{0}&apos;..
        /// </summary>
        internal static string SqlProgramDefinition_ValidateParameters_MustSpecifyParameterName {
            get {
                return ResourceManager.GetString("SqlProgramDefinition_ValidateParameters_MustSpecifyParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program called &apos;{0}&apos; only has &apos;{1}&apos; parameters, so does not match the supplied &apos;{2}&apos; parameters..
        /// </summary>
        internal static string SqlProgramDefinition_ValidateParameters_ParameterCountsNotEqual {
            get {
                return ResourceManager.GetString("SqlProgramDefinition_ValidateParameters_ParameterCountsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter named &apos;{0}&apos;, does not exist on the program called &apos;{1}&apos;..
        /// </summary>
        internal static string SqlProgramDefinition_ValidateParameters_ParameterDoesNotExist {
            get {
                return ResourceManager.GetString("SqlProgramDefinition_ValidateParameters_ParameterDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter named &apos;{0}&apos;, on the program called &apos;{1}&apos;, is of type &apos;{2}&apos; and so does not accept the CLR type &apos;{3}&apos;..
        /// </summary>
        internal static string SqlProgramDefinition_ValidateParameters_TypeDoesNotAcceptClrType {
            get {
                return ResourceManager.GetString("SqlProgramDefinition_ValidateParameters_TypeDoesNotAcceptClrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter named &apos;{0}&apos;, on the program called &apos;{1}&apos;, is of type &apos;{2}&apos; and so does not accept the SqlDbType &apos;{3}&apos;..
        /// </summary>
        internal static string SqlProgramDefinition_ValidateParameters_TypeDoesNotAcceptSqlDbType {
            get {
                return ResourceManager.GetString("SqlProgramDefinition_ValidateParameters_TypeDoesNotAcceptSqlDbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred whilst executing the &apos;{0}&apos; SqlProgram.  {1}.
        /// </summary>
        internal static string SqlProgramExecutionException_ErrorOccurredDuringExecution {
            get {
                return ResourceManager.GetString("SqlProgramExecutionException_ErrorOccurredDuringExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncating binary data of length &apos;{0}&apos; bytes when converting to SQL type &apos;{1}&apos; which only accepts &apos;{2}&apos; bytes..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_BinaryDataTruncated {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_BinaryDataTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured type &apos;{0}&apos; cannot accept an enumeration of &apos;{1}&apos;..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CannotAcceptEnumerationType {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CannotAcceptEnumerationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured type &apos;{0}&apos; cannot accept type &apos;{1}&apos;..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CannotAcceptType {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CannotAcceptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured type &apos;{0}&apos; cannot accept an enumeration of &apos;{1}&apos;.  Cannot cast &apos;{2}&apos; to &apos;{3}&apos; for the column with ordinal {4}..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CanNotCast {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CanNotCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured type &apos;{0}&apos; cannot accept an enumeration of &apos;{1}&apos;.  Cannot convert key type &apos;{2}&apos; to &apos;{3}&apos;..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CanNotConvertKeyType {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CanNotConvertKeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured type &apos;{0}&apos; cannot accept an enumeration of &apos;{1}&apos;.  The type only accepts {2} columns, but the tuple supplies &apos;{3}..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_ColumnNumberAndTupleSizeMismatch {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_ColumnNumberAndTupleSizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert binary data of length &apos;{0}&apos; bytes to SQL type &apos;{1}&apos; which only accepts &apos;{2}&apos; bytes..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CouldNotConvertBinaryData {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CouldNotConvertBinaryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert DateTime &apos;{0}&apos; to SQL type &apos;{1}&apos; which only accepts DateTimes in the &apos;{2}&apos; range..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CouldNotConvertDateTimeToSqlType {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CouldNotConvertDateTimeToSqlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert string of length &apos;{0}&apos; characters to SQL type &apos;{1}&apos; which only accepts &apos;{2}&apos; characters..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CouldNotConvertString {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CouldNotConvertString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not serialize object of type &apos;{0}&apos; into SQL type &apos;{1}&apos; as it requires &apos;{2}&apos; bytes and the SQL type only accepts &apos;{3}&apos; bytes..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_CouldNotSerializeObject {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_CouldNotSerializeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncating DateTime &apos;{0}&apos; when converting to SQL type &apos;{1}&apos; which only accepts DateTimes in the &apos;{2}&apos; range..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_DateTimeTruncated {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_DateTimeTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error whilst trying to create type convertor for &apos;{0}&apos; type on SQL Type &apos;{1}&apos;. {2}.
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_FatalErrorOccurred {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_FatalErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured type &apos;{0}&apos; was not created as a SqlTableType..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_NotCreatedAsSqlTableType {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_NotCreatedAsSqlTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No type specified for converting to SQL Type &apos;{0}&apos;..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_NoTypeSpecified {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_NoTypeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not pass string into SQL type &apos;{0}&apos; as it contains Unicode characters and the SQL type only accepts ASCII characters..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_StringContainsUnicodeCharacters {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_StringContainsUnicodeCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncating string of length &apos;{0}&apos; characters when converting to SQL type &apos;{1}&apos; which only accepts &apos;{2}&apos; characters..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_StringTruncated {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_StringTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDT type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_UdtTypeNotSupported {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_UdtTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losing Unicode characters when converting string into SQL type &apos;{0}&apos; as the SQL type only accepts ASCII characters..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_UnicodeCharactersLost {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_UnicodeCharactersLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported SqlDbType &apos;{0}&apos;..
        /// </summary>
        internal static string SqlType_GetClrToSqlConverter_UnsupportedSqlDbType {
            get {
                return ResourceManager.GetString("SqlType_GetClrToSqlConverter_UnsupportedSqlDbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown SQL system type found &apos;{0}&apos;, trying NVarChar..
        /// </summary>
        internal static string SqlType_UnknownSqlSystemType {
            get {
                return ResourceManager.GetString("SqlType_UnknownSqlSystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length: {0}; Precision: {1}; Scale: {2}..
        /// </summary>
        internal static string SqlTypeSize_ToString {
            get {
                return ResourceManager.GetString("SqlTypeSize_ToString", resourceCulture);
            }
        }
    }
}
