//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplications.Utilities.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplications.Utilities.Database.SQLResources", typeof(SQLResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	S.[schema_id] AS [SchemaID],
        ///	S.[name] AS [Name]
        ///FROM	sys.schemas AS S;
        ///
        ///SELECT	C.[name] AS [Name], 
        ///	COLLATIONPROPERTY(C.[name], &apos;CodePage&apos;) AS [CodePage],
        ///	COLLATIONPROPERTY(C.[name], &apos;LCID&apos;) AS [LCID],
        ///	COLLATIONPROPERTY(C.[name], &apos;ComparisonStyle&apos;) AS [ComparisonStyle], 
        ///	COLLATIONPROPERTY(C.[name], &apos;Version&apos;) AS [Version]
        ///FROM	sys.fn_helpcollations() C;
        ///
        ///SELECT	SERVERPROPERTY(&apos;collation&apos;) [ServerCollation],
        ///	D.[collation_name] AS [DatabaseCollation]
        ///FROM	sys.databases AS D
        ///WHERE	D. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetrieveSchema10 {
            get {
                return ResourceManager.GetString("RetrieveSchema10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	S.[schema_id] AS [SchemaID],
        ///	S.[name] AS [Name]
        ///FROM	sys.schemas AS S;
        ///
        ///SELECT	C.[name] AS [Name],
        ///	COLLATIONPROPERTY(C.[name], &apos;CodePage&apos;) AS [CodePage],
        ///	COLLATIONPROPERTY(C.[name], &apos;LCID&apos;) AS [LCID],
        ///	COLLATIONPROPERTY(C.[name], &apos;ComparisonStyle&apos;) AS [ComparisonStyle], 
        ///	COLLATIONPROPERTY(C.[name], &apos;Version&apos;) AS [Version]
        ///FROM	sys.fn_helpcollations() C;
        ///
        ///SELECT	SERVERPROPERTY(&apos;collation&apos;) [ServerCollation],
        ///	D.[collation_name] AS [DatabaseCollation]
        ///FROM	sys.databases AS D
        ///WHERE	D.[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetrieveSchema9 {
            get {
                return ResourceManager.GetString("RetrieveSchema9", resourceCulture);
            }
        }
    }
}
