//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplications.Utilities.PowerShell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplications.Utilities.PowerShell.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The dependency id &apos;{0}&apos; cannot contain a &apos;,&apos;..
        /// </summary>
        internal static string NuSpecDependency_DependencyIdContainsComma {
            get {
                return ResourceManager.GetString("NuSpecDependency_DependencyIdContainsComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dependency id cannot be empty..
        /// </summary>
        internal static string NuSpecDependency_DependencyIdEmpty {
            get {
                return ResourceManager.GetString("NuSpecDependency_DependencyIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; is not a valid dependency..
        /// </summary>
        internal static string NuSpecDependency_Parse_InvalidDependency {
            get {
                return ResourceManager.GetString("NuSpecDependency_Parse_InvalidDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nuget specification file &apos;{0}&apos; did not contain a package element from the nuspec namespace..
        /// </summary>
        internal static string NuSpecEditor_DoesNotContainPackageElement {
            get {
                return ResourceManager.GetString("NuSpecEditor_DoesNotContainPackageElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nuget specification file &apos;{0}&apos; did not contain a valid XML Document root node..
        /// </summary>
        internal static string NuSpecEditor_InvalidXmlDocumentRootNode {
            get {
                return ResourceManager.GetString("NuSpecEditor_InvalidXmlDocumentRootNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the nuget specification file &apos;{0}&apos;.
        /// </summary>
        internal static string NuSpecEditor_SpecificationFileNotFound {
            get {
                return ResourceManager.GetString("NuSpecEditor_SpecificationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution: {2}{0}{1}File name:{3}{0}{1}Projects:{4}{0}{1}Dependencies:{5}{0}.
        /// </summary>
        internal static string Solution_ToString {
            get {
                return ResourceManager.GetString("Solution_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot overwrite existing zip file &apos;{0}.
        /// </summary>
        internal static string Zip_Compress_CannotOverwriteExistingFile {
            get {
                return ResourceManager.GetString("Zip_Compress_CannotOverwriteExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the directory &apos;{0}&apos; to compress..
        /// </summary>
        internal static string Zip_Compress_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Zip_Compress_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; directory already exists, use the force option to overwrite..
        /// </summary>
        internal static string Zip_Decompress_Directory_Exists {
            get {
                return ResourceManager.GetString("Zip_Decompress_Directory_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the zip file &apos;{0}&apos;..
        /// </summary>
        internal static string Zip_Decompress_FileNotFound {
            get {
                return ResourceManager.GetString("Zip_Decompress_FileNotFound", resourceCulture);
            }
        }
    }
}
